// Main game engine for Spaced Penguin
// Based on the original game loop and GPS scripts

import { GameObject, Planet, Bonus, BonusPopup, Target, Slingshot, Arrow, TextObject, PointingArrow } from './gameObjects.js';
import { Penguin } from './penguin.js';
import { Physics } from './physics.js';
import Utils from './utils.js';
import { LevelLoader } from './levelLoader.js';
import { UIManager } from './uiManager.js';
import { LevelEndScreen } from './levelEndScreen.js';
import Console from './console.js';
import LevelEditor from './levelEditor.js';
import FullscreenManager from './fullscreenManager.js';
import plog from './penguinLogger.js';
import {
    applyGameSimulationEvents,
    invalidateGameSimulationState,
    stepGameSimulation
} from './gameSimulationAdapter.js';
import { calculateLaunchVelocity, calculateLevelScore } from './simulationEngine.js';
import {
    LevelObjectType,
    LevelOrbitType,
    levelObjectTypeFromClassName
} from './levelSchema.js';
import { LEVEL_CATALOG_CONFIG, LEVEL_DEFAULTS, PHYSICS_CONFIG, WORLD_CONFIG } from './config/gameConfig.js';
import { INPUT_CONFIG, isMobileViewport } from './config/inputConfig.js';
import { RENDER_CONFIG } from './config/renderConfig.js';
import { assetPath } from './config/assetConfig.js';
import { AudioCue, getAudioCue } from './config/audioConfig.js';
import { RUNTIME_CONFIG } from './config/runtimeConfig.js';
import {
    STAGE_WIDTH,
    STAGE_HEIGHT,
    applyViewportTransform,
    clearViewport,
    createViewport,
    screenToStage
} from './viewport.js';

const GameState = {
    MENU: 'menu',
    PLAYING: 'playing',
    PAUSED: 'paused',
    GAME_OVER: 'gameOver',
    SCORING: 'scoring',
    LEVEL_EDITOR: 'levelEditor'
};

class Game {
    constructor(canvas, assetLoader, audioManager) {
        plog.info('Game constructor called');
        this.canvas = canvas;
        this.ctx = canvas.getContext('2d');
        this.physics = new Physics();
        this.assetLoader = assetLoader;
        this.audioManager = audioManager;
        
        // Canvas scaling for responsive design
        this.canvasScaleX = 1;
        this.canvasScaleY = 1;
        
        // UI Manager for menus and overlays
        this.uiManager = new UIManager(canvas, audioManager);
        
        // Game state
        this.state = GameState.MENU;
        this.level = 1;
        this.score = 0;
        this.currentLevelBestScore = 0;
        this.currentAttemptScore = 0; // Track score for current attempt only
        this.distance = 0;
        this.tries = 0;
        this.highScore = 0;
        this.planetCollisions = 0; // Track planet collisions for rules
        
        // Level system
        this.levelLoader = new LevelLoader(assetLoader);
        this.levelRules = null;
        this.levelMetadata = {
            name: 'Custom Level 1',
            description: 'Generated by Level Editor'
        };
        
        // Bounds system (matching original game's pFlightRect/pStageRect)
        this.stageRect = { x: 0, y: 0, width: STAGE_WIDTH, height: STAGE_HEIGHT };
        this.flightRect = { ...WORLD_CONFIG.flightBounds };
        this.viewport = canvas.viewport || createViewport(STAGE_WIDTH, STAGE_HEIGHT, 1);
        this.viewRect = this.viewport.viewRect;
        
        // Game objects
        this.penguin = null;
        this.slingshot = null;
        this.launches = [];
        this.target = null;
        this.planets = [];
        this.bonuses = [];
        this.textObjects = [];
        this.pointingArrows = [];
        this.gameObjects = [];
        
        // Rendering optimizations
        this._cachedSortedObjects = null;
        this._gameObjectsChanged = true;
        
        // Bonus popup system
        this.bonusPopup = new BonusPopup(0, 0, 0);
        this.gameObjects.push(this.bonusPopup);
        
        // Initialize arrow after stage rect is set up
        this.arrow = new Arrow(0, 0);
        this.arrow.setStageRect(this.viewRect);
        this.arrow.setFlightRect(this.flightRect);
        this.gameObjects.push(this.arrow);

        // Responsive picture-in-picture view shown while Kevin is off-screen.
        // Ratios are based on the logical canvas, so the inset scales with the
        // parent viewport everywhere the main canvas does.
        this.kevinCam = RENDER_CONFIG.kevinCam;
        
        // Initialize console and level editor
        this.console = new Console(this);
        this.levelEditor = new LevelEditor(this);
        
        // Initialize fullscreen manager
        this.fullscreenManager = new FullscreenManager(
            canvas,
            canvas.parentElement,
            () => window.gameManager?.setupResponsiveCanvas()
        );
        
        // Pass ALL class references to level editor for object creation
        this.levelEditor.gameObjectClasses = {
            Planet,
            Bonus,
            BonusPopup,
            Target,
            Arrow,
            Slingshot,
            TextObject,
            PointingArrow
        };
        
        // Shot path tracing system (like original game)
        this.shotPaths = []; // Array of complete shot paths
        this.currentShotPath = []; // Current shot being recorded
        this.currentShotRenderPath = null;
        this.shotColors = RENDER_CONFIG.shotTrails.colors;
        this.currentColorIndex = 0;
        this.isRecordingPath = false;
        this._runtimeSimulationState = null;
        
        // Alpha mask system (matching original game's k1, k2, k3 sprites)
        this.alphaMasks = []; // Array of last 3 launch positions with alpha masks
        this.alphaMaskImage = null; // The Kev_Alph alpha mask image
        this.alphaMaskStencil = null;
        this.coloredAlphaMaskCanvases = new Map();
        this.loadAlphaMask();
        
        // Input handling
        this.mouseDown = false;
        this.mousePosition = { x: 0, y: 0 };
        this.isDragging = false;
        
        // Animation
        this.lastTime = 0;
        this.deltaTime = 0;
        
        // UI
        this.ui = {
            level: document.getElementById('level'),
            score: document.getElementById('score'),
            distance: document.getElementById('distance'),
            tries: document.getElementById('tries')
        };
        this._hudValues = Object.create(null);
        this._nextDistanceHudUpdate = 0;
        
        plog.debug('UI elements found:', this.ui);
        plog.debug('Asset loader available:', !!this.assetLoader);
        
        // Note: Input handling now managed by InputActionManager
        plog.success('Game constructor completed');
        // Don't load level immediately - wait for start
        this.stars = [];
        this.starfieldTime = 0;
        this.starDriftSpeed = RENDER_CONFIG.starfield.drift;
        this.generateStars();
    }
    
    setState(newState) {
        if (this.state !== newState) {
            plog.info(`Game state changing from ${this.state} to ${newState}`);
            this.state = newState;

            document.body.classList.toggle('is-menu', newState === GameState.MENU);
            if (newState !== GameState.MENU) {
                document.getElementById('mobileStartButton')?.remove();
            }
            
            // Notify InputActionManager of state change if available
            if (window.gameManager?.inputActionManager) {
                window.gameManager.inputActionManager.updateActiveActions();
            }
        }
    }
    
    // Input handling methods - called by InputActionManager
    // These methods are kept for backwards compatibility but input routing
    // is now handled by the InputActionManager system
    
    setupEventListeners() {
        // This method is now deprecated - input handling managed by InputActionManager
        console.warn('Game.setupEventListeners() is deprecated - input now managed by InputActionManager');
        
        // Still set touch action for mobile compatibility
        this.canvas.style.touchAction = 'none';
        
        // Add mobile-specific controls
        this.setupMobileControls();
    }
    
    setupMobileControls() {
        // Create mobile control buttons if on mobile
        if (this.isMobileDevice()) {
            this.createMobileControlButtons();
        }
    }
    
    isMobileDevice() {
        return isMobileViewport();
    }
    
    createMobileControlButtons() {
        // Remove existing buttons if any
        const existingButtons = document.querySelectorAll('.mobile-control-button, .mobile-ui-overlay');
        existingButtons.forEach(btn => btn.remove());
        
        // Create mobile UI overlay container
        this.mobileUIOverlay = document.createElement('div');
        this.mobileUIOverlay.className = 'mobile-ui-overlay';
        this.mobileUIOverlay.style.cssText = `
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            pointer-events: none;
            z-index: 150;
            font-family: Arial, sans-serif;
        `;
        
        // Create mobile control panel
        const controlPanel = document.createElement('div');
        controlPanel.style.cssText = `
            position: absolute;
            top: 10px;
            right: 10px;
            display: flex;
            flex-direction: column;
            gap: 8px;
            pointer-events: auto;
        `;
        
        // Create reset button
        const resetButton = document.createElement('button');
        resetButton.className = 'mobile-control-button';
        resetButton.textContent = '↻ TRY AGAIN';
        resetButton.style.cssText = `
            background: rgba(255, 100, 100, 0.9);
            color: white;
            border: none;
            padding: 12px 16px;
            border-radius: 25px;
            font-size: 14px;
            font-weight: bold;
            cursor: pointer;
            touch-action: manipulation;
            min-height: 44px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.3);
            backdrop-filter: blur(10px);
        `;
        
        resetButton.addEventListener('click', () => {
            if (this.state === GameState.PLAYING || (this.state === GameState.LEVEL_EDITOR && this.levelEditor.mode === 'play')) {
                this.tryAgain();
                // Haptic feedback
                if ('vibrate' in navigator) {
                    navigator.vibrate(INPUT_CONFIG.hapticsMs.mobileControl);
                }
            }
        });
        
        // Create quit button
        const quitButton = document.createElement('button');
        quitButton.className = 'mobile-control-button';
        quitButton.textContent = '✕ QUIT';
        quitButton.style.cssText = `
            background: rgba(128, 128, 128, 0.9);
            color: white;
            border: none;
            padding: 12px 16px;
            border-radius: 25px;
            font-size: 14px;
            font-weight: bold;
            cursor: pointer;
            touch-action: manipulation;
            min-height: 44px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.3);
            backdrop-filter: blur(10px);
        `;
        
        quitButton.addEventListener('click', () => {
            if (this.state === GameState.PLAYING || (this.state === GameState.LEVEL_EDITOR && this.levelEditor.mode === 'play')) {
                this.showQuitDialog();
            }
        });
        
        controlPanel.appendChild(resetButton);
        controlPanel.appendChild(quitButton);
        
        // Create mobile instruction overlay
        this.mobileInstructions = document.createElement('div');
        this.mobileInstructions.style.cssText = `
            position: absolute;
            bottom: 20px;
            left: 50%;
            transform: translateX(-50%);
            background: rgba(0, 0, 0, 0.8);
            color: white;
            padding: 12px 20px;
            border-radius: 25px;
            font-size: 14px;
            text-align: center;
            pointer-events: none;
            max-width: 90%;
            box-shadow: 0 2px 8px rgba(0,0,0,0.3);
            backdrop-filter: blur(10px);
            transition: opacity 0.3s ease;
        `;
        
        // Create launch visual feedback
        this.createLaunchFeedback();
        
        this.mobileUIOverlay.appendChild(controlPanel);
        this.mobileUIOverlay.appendChild(this.mobileInstructions);
        document.body.appendChild(this.mobileUIOverlay);
        
        // Update instructions based on current state
        this.updateMobileInstructions();
        
        // Auto-hide instructions after 5 seconds
        setTimeout(() => {
            if (this.mobileInstructions) {
                this.mobileInstructions.style.opacity = '0.6';
            }
        }, RUNTIME_CONFIG.mobileInstructionsFadeDelayMs);
    }
    
    createLaunchFeedback() {
        // Create visual feedback for slingshot aiming
        this.launchIndicator = document.createElement('div');
        this.launchIndicator.style.cssText = `
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            width: 100px;
            height: 100px;
            border: 3px solid rgba(0, 255, 255, 0.8);
            border-radius: 50%;
            pointer-events: none;
            opacity: 0;
            transition: all 0.2s ease;
            box-shadow: 0 0 20px rgba(0, 255, 255, 0.5);
        `;
        
        this.mobileUIOverlay.appendChild(this.launchIndicator);
    }
    
    updateMobileInstructions() {
        if (!this.mobileInstructions || !this.isMobileDevice()) return;
        
        let instructionText = '';
        
        switch (this.state) {
            case GameState.MENU:
                instructionText = '👆 Tap anywhere to start';
                break;
            case GameState.PLAYING:
                if (this.penguin && this.penguin.state === 'idle') {
                    instructionText = '🎯 Drag penguin to aim, release to launch';
                } else if (this.penguin && this.penguin.state === 'pullback') {
                    instructionText = '🎯 Release to launch!';
                } else if (this.penguin && this.penguin.state === 'soaring') {
                    instructionText = '👆 Tap to try again';
                } else {
                    instructionText = '🐧 Ready to launch!';
                }
                break;
            case GameState.LEVEL_EDITOR:
                if (this.levelEditor && this.levelEditor.mode === 'play') {
                    instructionText = '🎮 Testing level - drag to launch';
                } else {
                    instructionText = '✏️ Level Editor - long press to add objects';
                }
                break;
            default:
                instructionText = '👆 Touch to interact';
        }
        
        this.mobileInstructions.textContent = instructionText;
    }
    
    showLaunchFeedback(show = true) {
        if (this.launchIndicator) {
            this.launchIndicator.style.opacity = show ? '1' : '0';
            this.launchIndicator.style.transform = show ? 
                'translate(-50%, -50%) scale(1.2)' : 
                'translate(-50%, -50%) scale(1)';
        }
    }
    
    getMousePosition(e) {
        return screenToStage(this.canvas, this.viewport, e.clientX, e.clientY);
    }
    
    setCanvasScale(scaleX, scaleY) {
        this.canvasScaleX = scaleX;
        this.canvasScaleY = scaleY;
    }

    setViewport(viewport) {
        this.viewport = viewport;
        this.viewRect = viewport.viewRect;
        this.canvasScaleX = viewport.scale;
        this.canvasScaleY = viewport.scale;
        this.arrow?.setStageRect(this.viewRect);
    }

    beginFrame() {
        clearViewport(this.ctx, this.canvas);
        applyViewportTransform(this.ctx, this.viewport);
    }
    
    handleMouseDown(e) {
        this.mouseDown = true;
        this.mousePosition = this.getMousePosition(e);

        if (this.state === GameState.MENU) {
            this.startGame();
            return;
        }
        
        // Delegate to level editor if active AND in edit mode
        if (this.state === GameState.LEVEL_EDITOR && this.levelEditor.active && this.levelEditor.mode === 'edit') {
            this.levelEditor.handleMouseDown(e);
            return;
        }
        
        // Allow slingshot in both playing state and level editor play mode
        const canUseSlingshot = (this.state === GameState.PLAYING) || 
                              (this.state === GameState.LEVEL_EDITOR && this.levelEditor.mode === 'play');
        
        if (canUseSlingshot && this.penguin.state === 'idle') {
            this.isDragging = true;
            this.slingshot.startPull(this.mousePosition.x, this.mousePosition.y);
            this.penguin.setState('pullback');
            
            // Show visual feedback for mobile
            if (this.isMobileDevice()) {
                this.showLaunchFeedback(true);
                this.updateMobileInstructions();
            }
        }
    }
    
    handleMouseMove(e) {
        this.mousePosition = this.getMousePosition(e);
        
        // Delegate to level editor if active AND in edit mode
        if (this.state === GameState.LEVEL_EDITOR && this.levelEditor.active && this.levelEditor.mode === 'edit') {
            this.levelEditor.handleMouseMove(e);
            return;
        }
        
        if (this.isDragging && this.slingshot.isPulling) {
            this.slingshot.updatePullback(this.mousePosition.x, this.mousePosition.y);
        }
    }
    
    handleMouseUp(e) {
        this.mouseDown = false;
        
        // Delegate to level editor if active AND in edit mode
        if (this.state === GameState.LEVEL_EDITOR && this.levelEditor.active && this.levelEditor.mode === 'edit') {
            this.levelEditor.handleMouseUp(e);
            return;
        }
        
        if (this.isDragging) {
            this.isDragging = false;
            const velocity = this.slingshot.release();
            this.launchPenguin(velocity, this.slingshot.lastLaunch);
            
            // Hide visual feedback for mobile
            if (this.isMobileDevice()) {
                this.showLaunchFeedback(false);
                this.updateMobileInstructions();
            }
        } else {
            // Mouse click during soaring triggers tryAgain (like original)
            const canUseSlingshot = (this.state === GameState.PLAYING) || 
                                  (this.state === GameState.LEVEL_EDITOR && this.levelEditor.mode === 'play');
            if (canUseSlingshot && this.penguin && this.penguin.state === 'soaring') {
                this.tryAgain();
            }
        }
    }
    
    handleTouchStart(e) {
        e.preventDefault();
        e.stopPropagation();
        
        if (e.touches.length > 0) {
            const touch = e.touches[0];
            
            // Create a synthetic mouse event
            const mouseEvent = {
                clientX: touch.clientX,
                clientY: touch.clientY,
                preventDefault: () => {},
                stopPropagation: () => {}
            };
            
            this.handleMouseDown(mouseEvent);
        }
    }
    
    handleTouchMove(e) {
        e.preventDefault();
        e.stopPropagation();
        
        if (e.touches.length > 0) {
            const touch = e.touches[0];
            
            // Create a synthetic mouse event
            const mouseEvent = {
                clientX: touch.clientX,
                clientY: touch.clientY,
                preventDefault: () => {},
                stopPropagation: () => {}
            };
            
            this.handleMouseMove(mouseEvent);
        }
    }
    
    handleTouchEnd(e) {
        e.preventDefault();
        e.stopPropagation();
        
        // Create a synthetic mouse event
        const mouseEvent = {
            clientX: 0,
            clientY: 0,
            preventDefault: () => {},
            stopPropagation: () => {}
        };
        
        this.handleMouseUp(mouseEvent);
    }
    
    handleKeyDown(e) {
        // Handle console toggle first
        if (e.key === '`') {
            e.preventDefault();
            this.console.toggle();
            return;
        }
        
        // Don't process other keys if console is open
        if (this.console.visible) {
            return;
        }
        
        // Check if we should allow play mode keys
        const canUsePlayKeys = (this.state === GameState.PLAYING) || 
                              (this.state === GameState.LEVEL_EDITOR && this.levelEditor.mode === 'play');
        
        switch (e.key.toLowerCase()) {
            case 'q':
                if (canUsePlayKeys) {
                    this.showQuitDialog();
                }
                break;
            case 'r':
                if (canUsePlayKeys) {
                    this.tryAgain();
                }
                break;
            case ' ':
                // Only allow spacebar to start game on desktop
                // But don't interfere if InputActionManager already handled it
                if (this.state === GameState.MENU && !this.isMobileDevice() && !e.defaultPrevented) {
                    console.log('Game class: Handling space key for menu');
                    this.startGame();
                } else if (this.state === GameState.MENU && e.defaultPrevented) {
                    console.log('Game class: Space key already handled by InputActionManager');
                }
                break;
            default:
                // Any other key during playing triggers tryAgain (like original)
                if (canUsePlayKeys && this.penguin && this.penguin.state === 'soaring') {
                    this.tryAgain();
                }
                break;
        }
    }
    
    launchPenguin(velocity, launch = null) {
        plog.soar('Game launchPenguin called with velocity:', velocity);

        if (launch) {
            this.launches.push({ angle: launch.angle, power: launch.power });
        }
        
        // Create alpha mask at current launch position (matching original game's setUpSnapping)
        this.createAlphaMaskAtLaunchPosition();
        
        this.penguin.launch(velocity.x, velocity.y);
        this.penguin.setState('soaring');
        this.tries++;
        this.invalidateSimulationState();
        this.updateUI();
        
        // Play launch sound
        this.playSound(getAudioCue(AudioCue.LAUNCH).soundId);
        
        // Clear physics trace
        this.physics.clearTrace();
        
        // Start recording shot path
        this.startRecordingShotPath();
        

    }

    launchTestTrajectory(angle, power) {
        if (!Number.isFinite(angle) || !Number.isFinite(power)) {
            throw new Error('Launch angle and power must be finite numbers');
        }

        // Headless samples always begin from a freshly loaded level. Reloading
        // here also resets orbiting objects to simulation time zero so the live
        // game starts from the exact same world state.
        this.loadLevel(this.level);
        this.setState(GameState.PLAYING);

        const velocity = calculateLaunchVelocity(angle, power, {
            velocityMultiplier: this.slingshot.velocityMultiplier,
            maxPullback: this.slingshot.maxPullback,
            minPullback: this.slingshot.minPullback
        });
        this.launchPenguin(velocity, { angle, power });
        return velocity;
    }
    
    // Shot path recording methods (matching original game behavior)
    startRecordingShotPath() {
        this.isRecordingPath = true;
        this.currentShotPath = [];
        this.currentShotRenderPath = typeof Path2D === 'function' ? new Path2D() : null;
        plog.waddle(`Started recording shot path ${this.shotPaths.length + 1} with color ${this.shotColors[this.currentColorIndex]}`);
    }
    
    recordPathPoint(x, y) {
        if (!this.isRecordingPath || this.penguin.state === 'crashed') return;
        const previous = this.currentShotPath.at(-1);
        if (previous && x === previous.x && y === previous.y) {
            return;
        }

        if (this.currentShotRenderPath) {
            if (previous) {
                this.currentShotRenderPath.lineTo(x, y);
            } else {
                this.currentShotRenderPath.moveTo(x, y);
            }
        }
        this.currentShotPath.push({ x, y });
    }
    
    endRecordingShotPath() {
        if (this.isRecordingPath && this.currentShotPath.length > 1) {
            // Store the complete path with its color
            const shotPath = {
                points: this.currentShotPath,
                renderPath: this.currentShotRenderPath,
                color: this.shotColors[this.currentColorIndex],
                shotNumber: this.shotPaths.length + 1
            };
            
            this.shotPaths.push(shotPath);
            if (this.shotPaths.length > RENDER_CONFIG.shotTrails.maximumCompletedPaths) {
                this.shotPaths.shift();
            }
            plog.waddle(`Saved shot path ${shotPath.shotNumber} with ${shotPath.points.length} points in color ${shotPath.color}`);
            
            // Cycle to next color
            this.currentColorIndex = (this.currentColorIndex + 1) % this.shotColors.length;
        }
        
        this.isRecordingPath = false;
        this.currentShotPath = [];
        this.currentShotRenderPath = null;
    }
    
    clearAllShotPaths() {
        this.shotPaths = [];
        this.currentShotPath = [];
        this.currentShotRenderPath = null;
        this.currentColorIndex = 0;
        this.isRecordingPath = false;
        plog.debug('Cleared all shot paths');
    }
    
    drawAllShotPaths(ctx) {
        // Draw all completed shot paths
        for (const shotPath of this.shotPaths) {
            if (shotPath.points.length < 2) continue;
            
            ctx.save();
            ctx.strokeStyle = shotPath.color;
            ctx.lineWidth = RENDER_CONFIG.shotTrails.lineWidth;
            ctx.globalAlpha = RENDER_CONFIG.shotTrails.completedAlpha;
            ctx.lineCap = 'round';
            ctx.lineJoin = 'round';
            
            ctx.beginPath();
            if (shotPath.renderPath) {
                ctx.stroke(shotPath.renderPath);
            } else {
                ctx.moveTo(shotPath.points[0].x, shotPath.points[0].y);
                for (let i = 1; i < shotPath.points.length; i++) {
                    ctx.lineTo(shotPath.points[i].x, shotPath.points[i].y);
                }
                ctx.stroke();
            }
            ctx.restore();
        }
        
        // Draw current shot path being recorded (if any) with slightly different style
        if (this.isRecordingPath && this.currentShotPath.length > 1) {
            ctx.save();
            ctx.strokeStyle = this.shotColors[this.currentColorIndex];
            ctx.lineWidth = RENDER_CONFIG.shotTrails.lineWidth;
            ctx.globalAlpha = RENDER_CONFIG.shotTrails.activeAlpha;
            ctx.lineCap = 'round';
            ctx.lineJoin = 'round';
            
            ctx.beginPath();
            if (this.currentShotRenderPath) {
                ctx.stroke(this.currentShotRenderPath);
            } else {
                ctx.moveTo(this.currentShotPath[0].x, this.currentShotPath[0].y);
                for (let i = 1; i < this.currentShotPath.length; i++) {
                    ctx.lineTo(this.currentShotPath[i].x, this.currentShotPath[i].y);
                }
                ctx.stroke();
            }
            ctx.restore();
        }
    }
    
    drawAlphaMasks(ctx) {
        if (this.alphaMasks.length === 0) return;
        
        // Draw alpha masks in reverse order (oldest first, newest last)
        for (let i = this.alphaMasks.length - 1; i >= 0; i--) {
            const mask = this.alphaMasks[i];
            if (!mask.renderCanvas) continue;
            
            ctx.save();
            ctx.globalAlpha = mask.alpha;
            ctx.translate(mask.x, mask.y);

            // Draw the result centered on the launch position
            // Use the registration point from the original game: [8, 13]
            ctx.drawImage(mask.renderCanvas, -8, -13);
            
            ctx.restore();
        }
    }
    
    update(deltaTime) {
        this.deltaTime = deltaTime;
        this.starfieldTime = (this.starfieldTime || 0) + deltaTime;
        
        // Update UI Manager
        this.uiManager.update(deltaTime);
        
        // Only states with a fully loaded, actively playing world may enter the
        // deterministic simulation. Menu construction intentionally has no
        // penguin, target, or slingshot yet.
        const shouldStepWorld = this.state === GameState.PLAYING ||
            (this.state === GameState.LEVEL_EDITOR && this.levelEditor?.mode === 'play');
        if (!shouldStepWorld) {
            return;
        }

        const simulationResult = this.updateSimulation(deltaTime);
        this.updateGameObjects(deltaTime, { updateOrbit: false });
        applyGameSimulationEvents(this, simulationResult.events, deltaTime);
    }

    updateSimulation(deltaTime) {
        return stepGameSimulation(this, deltaTime);
    }

    updateGameObjects(deltaTime, options = {}) {
        // Update game objects with optimized loop
        const gameObjectCount = this.gameObjects.length;
        for (let i = 0; i < gameObjectCount; i++) {
            const obj = this.gameObjects[i];

            // Penguin movement, trail, and animation are updated by the
            // dedicated state-specific path below. Updating it here as well
            // advances the simulation twice per rendered frame.
            if (obj === this.penguin) continue;

            if (obj.constructor.name === 'Arrow') {
                // Only update arrow if penguin exists and has position AND is soaring
                if (this.penguin && this.penguin.position && this.penguin.state === 'soaring') {
                    obj.update(this.penguin);
                } else {
                    // Make sure arrow is hidden when penguin is not soaring
                    obj.visible = false;
                }
            } else {
                obj.update(deltaTime, options);
            }
        }
    }
    
    handleTargetHit() {
        this.playSound(getAudioCue(AudioCue.ENTER_SHIP).soundId);
        
        // Stop the target's hit timer so ship stays closed during scoring
        if (this.target && this.target.isHit) {
            this.target.isHit = false;
            this.target.hitFrameCount = 0;
        }
        
        // Wait a moment before showing scoring (matches original 30 frame delay)
        setTimeout(() => {
            this.showLevelEndScreen();
        }, RUNTIME_CONFIG.levelEndTransitionDelayMs);
    }
    
    calculateFinalScore() {
        const result = calculateLevelScore({
            distance: this.distance,
            level: this.level,
            tries: this.tries,
            attemptBonus: this.currentAttemptScore,
            totalScore: this.score,
            previousLevelContribution: this.currentLevelBestScore,
            multiplier: this.levelRules?.scoreMultiplier ?? 1
        });
        const levelScore = result.levelScore;
        this.currentLevelBestScore = result.levelContribution;
        this.score = result.totalScore;
        this.lastScoreImprovement = result.scoreImprovement;
        
        this.updateUI();
        
        // Check for high score
        if (this.score > this.highScore) {
            this.highScore = this.score;
            this.saveHighScore();
        }
        
        return levelScore;
    }
    
    showLevelEndScreen() {
        if (this.state === GameState.SCORING) return null;
        this.setState(GameState.SCORING);
        this.calculateFinalScore();
        return this.uiManager.showScreen(LevelEndScreen, this);
    }
    
    nextLevel() {
        this.level++;
        this.currentLevelBestScore = 0;
        this.tries = 0;
        this.distance = 0;
        this.planetCollisions = 0;
        
        // Close any UI screens
        this.uiManager.closeAllScreens();
        
        // Load next level
        this.loadLevel(this.level);
        
        // Update URL parameter to reflect current level
        Utils.setURLParameter('level', this.level.toString());
        
        // Return to playing state
        this.setState(GameState.PLAYING);
    }
    
    resetLevel() {
        this.tries = 0;
        this.launches = [];
        this.distance = 0;
        this.currentAttemptScore = 0;
        this.planetCollisions = 0;
        this.resetPenguin();
        this.resetBonuses();
        this.physics.clearTrace();
        this.clearAllShotPaths();
        this.clearAlphaMasks();
        this.arrow.visible = false; // Reset arrow visibility
        this.setState(GameState.PLAYING);
    }
    
    resetPenguin() {
        this.penguin.reset();
        this.resetPenguinToSlingshot();
        this.arrow.visible = false; // Reset arrow visibility
    }
    
    resetBonuses() {
        for (const bonus of this.bonuses) {
            bonus.reset(); // Use the new reset method
        }
        
        // Reset bonus popup
        if (this.bonusPopup) {
            this.bonusPopup.visible = false;
            this.bonusPopup.state = 'idle';
        }
    }
    
    loadLevel(level) {
        // Validate before clearing the current world so a bad definition cannot
        // leave the game half-loaded.
        this.levelLoader.assertLevelValid(level);
        this.invalidateSimulationState();

        // Clear existing game state
        this.gameObjects = [];
        this.planets = [];
        this.bonuses = [];
        this.physics.clear();
        this.planetCollisions = 0;
        this.tries = 0;
        this.launches = [];
        this.distance = 0;
        this.currentAttemptScore = 0; // Reset attempt score for new level
        
        // Clear all shot path traces for new level
        this.clearAllShotPaths();
        this.clearAlphaMasks();
        
        // IMPORTANT: Invalidate render cache when clearing gameObjects
        this._cachedSortedObjects = null;
        this._gameObjectsChanged = true;
        
        // Load level through level loader first
        const result = this.levelLoader.loadLevel(level, this);
        
        // Add arrow AFTER level loader has finished (so it doesn't get cleared)
        this.arrow = new Arrow(0, 0);
        this.arrow.setStageRect(this.viewRect);
        this.arrow.setFlightRect(this.flightRect);
        this.gameObjects.push(this.arrow);
        
        // Re-add bonus popup system
        this.bonusPopup = new BonusPopup(0, 0, 0);
        this.gameObjects.push(this.bonusPopup);
        
        // Force render cache update since we added objects
        this._gameObjectsChanged = true;
        
        return result;
    }
    
    // Helper methods for game object management
    addGameObject(obj) {
        this.gameObjects.push(obj);
        this._gameObjectsChanged = true;
    }
    
    removeGameObject(obj) {
        const index = this.gameObjects.indexOf(obj);
        if (index !== -1) {
            this.gameObjects.splice(index, 1);
            this._gameObjectsChanged = true;
        }
    }
    
    // Object pool management
    getPooledObject(type) {
        const pool = this._objectPools[type];
        if (pool && pool.length > 0) {
            return pool.pop();
        }
        return null;
    }
    
    returnToPool(obj, type) {
        const pool = this._objectPools[type];
        if (pool && pool.length < 10) { // Limit pool size
            obj.reset?.(); // Reset object state if method exists
            pool.push(obj);
        }
    }

    
    render() {
        this.beginFrame();
        
        // Draw background stars (cached)
        this.drawStars();
        
        // Keep trajectory lines and trail marks inside the authored playfield.
        this.drawPlayfieldTraces();
        
        // Cache sorted objects if game objects haven't changed
        if (!this._cachedSortedObjects || this._gameObjectsChanged) {
            this._cachedSortedObjects = [...this.gameObjects].sort((a, b) => {
                const orderA = a.renderOrder || 0;
                const orderB = b.renderOrder || 0;
                return orderA - orderB;
            });
            this._gameObjectsChanged = false;
        }
        
        // Draw all game objects in render order
        const objCount = this._cachedSortedObjects.length;
        for (let i = 0; i < objCount; i++) {
            const object = this._cachedSortedObjects[i];
            if (object === this.penguin) {
                this.drawPenguinInPlayfield();
            } else {
                object.draw(this.ctx);
            }
        }

        // Keep this tied to Arrow.visible so both off-screen indicators always
        // appear and disappear together.
        this.drawKevinCam();
        
        // Draw UI overlays
        this.drawUI();
        
        // Draw UI Manager screens on top
        this.uiManager.render();
        
        // Draw level editor overlay
        this.levelEditor.render(this.ctx);
    }

    drawPlayfieldTraces() {
        const playfield = this.stageRect || {
            x: 0,
            y: 0,
            width: STAGE_WIDTH,
            height: STAGE_HEIGHT
        };

        this.ctx.save();
        this.ctx.beginPath();
        this.ctx.rect(playfield.x, playfield.y, playfield.width, playfield.height);
        this.ctx.clip();

        this.drawAllShotPaths(this.ctx);
        this.drawAlphaMasks(this.ctx);
        this.physics.drawTrace(this.ctx);

        this.ctx.restore();
    }

    drawPenguinInPlayfield() {
        if (!this.penguin) {
            return;
        }

        const playfield = this.stageRect || {
            x: 0,
            y: 0,
            width: STAGE_WIDTH,
            height: STAGE_HEIGHT
        };

        this.ctx.save();
        this.ctx.beginPath();
        this.ctx.rect(playfield.x, playfield.y, playfield.width, playfield.height);
        this.ctx.clip();
        this.penguin.draw(this.ctx);
        this.ctx.restore();
    }

    drawKevinCam() {
        if (!this.arrow?.visible || !this.penguin || this.penguin.state !== 'soaring') {
            return;
        }

        const config = { ...RENDER_CONFIG.kevinCam, ...this.kevinCam };
        const viewRect = this.viewRect || this.stageRect || {
            x: 0,
            y: 0,
            width: STAGE_WIDTH,
            height: STAGE_HEIGHT
        };
        const width = Math.max(
            config.minWidth,
            Math.min(viewRect.width * config.widthRatio, config.maxWidth)
        );
        const height = width / config.aspectRatio;
        const x = viewRect.x + config.margin;
        const y = viewRect.y + viewRect.height - height - config.margin;
        const contentY = y + config.headerHeight;
        const contentHeight = height - config.headerHeight;
        const centerX = x + width / 2;
        const centerY = contentY + contentHeight / 2;

        this.ctx.save();

        // Frame and header.
        this.ctx.shadowColor = config.shadowColor;
        this.ctx.shadowBlur = config.shadowBlur;
        this.ctx.fillStyle = config.backgroundColor;
        this.ctx.fillRect(x, y, width, height);
        this.ctx.shadowBlur = 0;
        this.ctx.fillStyle = config.headerColor;
        this.ctx.fillRect(x, y, width, config.headerHeight);

        // A deliberately goofy, hand-lettered label.
        const label = config.label;
        const colors = config.labelColors;
        this.ctx.font = config.labelFont;
        this.ctx.textAlign = 'center';
        this.ctx.textBaseline = 'middle';
        const letterSpacing = config.labelLetterSpacing;
        const labelStart = centerX - ((label.length - 1) * letterSpacing) / 2;
        for (let i = 0; i < label.length; i++) {
            this.ctx.save();
            this.ctx.translate(labelStart + i * letterSpacing, y + config.headerHeight / 2 + (i % 2 ? 2 : -1));
            this.ctx.rotate((i % 2 ? 1 : -1) * 0.08);
            this.ctx.fillStyle = colors[i % colors.length];
            this.ctx.fillText(label[i], 0, 0);
            this.ctx.restore();
        }

        // Clip the live view so Kevin and his trail cannot cover the frame.
        this.ctx.beginPath();
        this.ctx.rect(x + 3, contentY, width - 6, contentHeight - 3);
        this.ctx.clip();

        // Parallax stars keep the inset visibly moving even far beyond the
        // authored stage. Wrapping makes the field continuous in every direction.
        this.ctx.fillStyle = config.starColor;
        for (let i = 0; i < config.starCount; i++) {
            const rawX = i * 67.31 - this.penguin.x * 0.12;
            const rawY = i * i * 19.17 - this.penguin.y * 0.12;
            const starX = x + 4 + ((rawX % (width - 8)) + (width - 8)) % (width - 8);
            const starY = contentY + 3 + ((rawY % (contentHeight - 6)) + (contentHeight - 6)) % (contentHeight - 6);
            const size = i % 7 === 0 ? 2 : 1;
            this.ctx.globalAlpha = i % 3 === 0 ? 0.9 : 0.55;
            this.ctx.fillRect(starX, starY, size, size);
        }
        this.ctx.globalAlpha = 1;

        // Reuse Kevin's current animation frame and trail, translated into the
        // center of this local camera rather than advancing a separate animation.
        this.ctx.translate(centerX - this.penguin.x * config.zoom, centerY - this.penguin.y * config.zoom);
        this.ctx.scale(config.zoom, config.zoom);
        this.penguin.draw(this.ctx);
        this.ctx.restore();

        // Crisp border is drawn last so it remains above the clipped camera view.
        this.ctx.save();
        this.ctx.strokeStyle = config.borderColor;
        this.ctx.lineWidth = config.borderWidth;
        this.ctx.strokeRect(x + 1.5, y + 1.5, width - 3, height - 3);
        this.ctx.restore();
    }
    
    generateStars() {
        // Generate 100 random, spaced-out stars
        const numStars = RENDER_CONFIG.starfield.count;
        const minDist = RENDER_CONFIG.starfield.minimumDistance;
        const maxTries = RENDER_CONFIG.starfield.placementAttempts;
        this.stars = [];
        for (let i = 0; i < numStars; i++) {
            let tries = 0;
            let x, y, size;
            let ok = false;
            while (!ok && tries < maxTries) {
                x = Math.random() * STAGE_WIDTH;
                y = Math.random() * STAGE_HEIGHT;
                size = RENDER_CONFIG.starfield.minimumSize +
                    Math.floor(Math.random() * RENDER_CONFIG.starfield.sizeVariants);
                ok = true;
                for (const s of this.stars) {
                    const dx = s.x - x;
                    const dy = s.y - y;
                    if (Math.sqrt(dx*dx + dy*dy) < minDist) {
                        ok = false;
                        break;
                    }
                }
                tries++;
            }
            this.stars.push({ x, y, size });
        }
    }
    
    drawStars() {
        // The playfield camera is static, so its stars drift independently of
        // Kevin. Each size is a depth layer: larger/nearer stars move faster.
        const elapsed = this.starfieldTime || 0;
        const drift = this.starDriftSpeed || RENDER_CONFIG.starfield.drift;

        this.ctx.fillStyle = RENDER_CONFIG.starfield.color;
        for (const star of this.stars) {
            const rawX = star.x + elapsed * drift.x * star.size;
            const rawY = star.y + elapsed * drift.y * star.size;
            const x = ((rawX % STAGE_WIDTH) + STAGE_WIDTH) % STAGE_WIDTH;
            const y = ((rawY % STAGE_HEIGHT) + STAGE_HEIGHT) % STAGE_HEIGHT;

            this.ctx.globalAlpha = RENDER_CONFIG.starfield.baseAlpha +
                star.size * RENDER_CONFIG.starfield.sizeAlpha;
            this.ctx.fillRect(x, y, star.size, star.size);
        }
        this.ctx.globalAlpha = 1.0;
    }
    
    drawUI() {
        // Draw shot path info (debugging/status display)
        if (this.state === GameState.PLAYING) {
            this.ctx.save();
            this.ctx.fillStyle = '#FFFFFF';
            this.ctx.font = '14px Arial';
            this.ctx.textAlign = 'left';
            
            // Show recorded shot paths count
            //this.ctx.fillText(`Shot Paths: ${this.shotPaths.length}`, 10, this.canvas.height - 60);
            
            // Show current recording status
            if (this.isRecordingPath) {
                this.ctx.fillStyle = this.shotColors[this.currentColorIndex];
                //this.ctx.fillText(`Recording Path ${this.shotPaths.length + 1} (${this.currentShotPath.length} points)`, 10, this.canvas.height - 40);
            }
            
            this.ctx.restore();
        }
    }
    
    updateUI() {
        this._hudValues ||= Object.create(null);
        this.updateHudValue('level', this.level);
        this.updateHudValue('score', Utils.formatScore(this.score + this.currentAttemptScore));
        this.updateHudValue('tries', this.tries);

        const simulationTime = this.simulationTime || 0;
        if (
            this.state !== GameState.PLAYING ||
            this.distance === 0 ||
            simulationTime >= (this._nextDistanceHudUpdate || 0)
        ) {
            this.updateHudValue('distance', Math.floor(this.distance));
            this._nextDistanceHudUpdate = simulationTime + 0.1;
        }
    }

    updateHudValue(key, value) {
        const text = String(value);
        if (this._hudValues[key] === text) return;
        this._hudValues[key] = text;
        if (this.ui[key]) this.ui[key].textContent = text;
    }

    invalidateSimulationState() {
        invalidateGameSimulationState(this);
    }
    
    playSound(soundName) {
        // Use audio manager to play sounds
        if (this.audioManager) {
            this.audioManager.playSound(soundName);
        }
    }
    
    showQuitDialog() {
        if (this.quitDialog && this.uiManager.activeScreens.includes(this.quitDialog)) return this.quitDialog;

        const previousState = this.state;
        if (previousState === GameState.PLAYING) this.setState(GameState.PAUSED);

        this.quitDialog = this.uiManager.showConfirmation({
            title: 'Return to Menu?',
            message: 'Your progress in the current level will be lost.',
            confirmLabel: 'RETURN TO MENU',
            cancelLabel: 'KEEP PLAYING',
            onConfirm: () => {
                this.quitDialog = null;
                this.setState(GameState.MENU);
            },
            onCancel: () => {
                this.quitDialog = null;
                if (previousState === GameState.PLAYING || previousState === GameState.PAUSED) {
                    this.setState(GameState.PLAYING);
                }
            }
        });
        return this.quitDialog;
    }
    
    showMessage(message) {
        // Simple alert for now - could be enhanced with UI overlay
        alert(message);
    }
    
    startGame() {
        this.level = 1;
        this.score = 0;
        this.currentLevelBestScore = 0;
        this.currentAttemptScore = 0;
        this.distance = 0;
        this.tries = 0;
        this.loadLevel(this.level);
        this.setState(GameState.PLAYING);
    }
    
    jumpToLevel(targetLevel) {
        // Validate level exists (check if level file is available)
        const { firstLevel, maxGeneratedLevel } = LEVEL_CATALOG_CONFIG;
        if (targetLevel < firstLevel || targetLevel > maxGeneratedLevel) {
            plog.error(`Invalid level: ${targetLevel}. Must be ${firstLevel}-${maxGeneratedLevel}.`);
            return false;
        }
        
        plog.info(`Jumping to level ${targetLevel}`);
        
        // Set up game state for the target level
        this.level = targetLevel;
        this.score = 0; // Start fresh for testing purposes
        this.currentLevelBestScore = 0;
        this.currentAttemptScore = 0;
        this.distance = 0;
        this.tries = 0;
        this.planetCollisions = 0;
        
        // Close any UI screens
        this.uiManager.closeAllScreens();
        
        // Load the target level
        try {
            this.loadLevel(this.level);
            this.setState(GameState.PLAYING);
            
            // Update URL parameter to reflect current level
            Utils.setURLParameter('level', this.level.toString());
            
            plog.success(`Successfully jumped to level ${targetLevel}`);
            return true;
        } catch (error) {
            plog.error(`Failed to load level ${targetLevel}: ${error.message}`);
            
            // Fall back to level 1 if the target level doesn't exist
            this.level = 1;
            this.loadLevel(this.level);
            this.setState(GameState.PLAYING);
            Utils.removeURLParameter('level');
            
            return false;
        }
    }
    
    saveHighScore() {
        localStorage.setItem('spacedPenguinHighScore', this.highScore.toString());
    }
    
    loadHighScore() {
        const saved = localStorage.getItem('spacedPenguinHighScore');
        if (saved) {
            this.highScore = parseInt(saved);
        }
    }

    resetPenguinToSlingshot() {
        if (this.penguin && this.slingshot) {
            this.penguin.setPosition(this.slingshot.anchor.x, this.slingshot.anchor.y);
            this.penguin.setState('idle');
            this.penguin.reset();
            this.slingshot.isPulling = false;
            this.isDragging = false;
            this.mouseDown = false;
        }
        this.invalidateSimulationState();
        plog.waddle(`Penguin reset to position: ${this.penguin.x}, ${this.penguin.y}, state: ${this.penguin.state}`);
    }
    
    resetSlingshotState() {
        if (this.slingshot) {
            this.slingshot.isPulling = false;
        }
        this.isDragging = false;
        this.mouseDown = false;
        
        // Reset penguin to idle state regardless of current state
        if (this.penguin) {
            this.penguin.setState('idle');
            // Also reset penguin physics state
            this.penguin.launched = false;
            this.penguin.vx = 0;
            this.penguin.vy = 0;
        }
    }
    
    // Add tryAgain method (matching original GPS script)
    tryAgain() {
        plog.waddle('tryAgain called - immediately resetting penguin and bonuses');
        this.endRecordingShotPath();
        this.resetPenguinToSlingshot();
        this.resetBonuses(); // Reset bonuses between tries
        
        // Reset current attempt score (don't add bonuses until level is completed)
        this.currentAttemptScore = 0;
        
        // Reset distance (prevents accumulation across retries affecting score)
        this.distance = 0;
        
        // Update mobile UI feedback
        if (this.isMobileDevice()) {
            this.showLaunchFeedback(false);
            this.updateMobileInstructions();
        }
        
        this.updateUI();
    }
    
    // Level Editor Methods
    enterLevelEditor() {
        this.levelEditor.enter();
    }
    
    exitLevelEditor() {
        this.levelEditor.exit();
    }
    
    exportCurrentLevel() {
        plog.info('=== STARTING COMPREHENSIVE LEVEL EXPORT ===');
        
        // Prefer slingshot anchor for the canonical start position. If no slingshot,
        // fall back to penguin position, then defaults.
        const startPosForExport = this.slingshot && this.slingshot.position
            ? { x: this.slingshot.position.x, y: this.slingshot.position.y }
            : (this.penguin
                ? { x: this.penguin.x, y: this.penguin.y }
                : { ...WORLD_CONFIG.defaultStartPosition });

        const levelData = {
            name: this.levelMetadata?.name || `Custom Level ${this.level}`,
            description: this.levelMetadata?.description ?? '',
            startPosition: startPosForExport,
            targetPosition: this.target
                ? { x: this.target.position.x, y: this.target.position.y }
                : { ...WORLD_CONFIG.defaultTargetPosition },
            objects: [],
            rules: this.levelRules ? this.exportLevelRules() : {
                maxTries: null,
                timeLimit: null,
                scoreMultiplier: LEVEL_DEFAULTS.rules.scoreMultiplier
            }
        };
        
        // GREEDY EXPORT: Get ALL objects from ALL arrays
        const allObjects = this.getAllObjectsForExport();
        
        plog.info(`Found ${allObjects.length} total objects to export`);
        
        // Export each object with ALL its properties
        for (const obj of allObjects) {
            const exportedObj = this.exportObjectComprehensively(obj);
            if (exportedObj) {
                levelData.objects.push(exportedObj);
            }
        }
        
        plog.success(`Export complete: ${levelData.objects.length} objects exported`);
        plog.debug('Level data structure:', levelData);
        return levelData;
    }
    
    getAllObjectsForExport() {
        const allObjects = new Set(); // Use Set to avoid duplicates
        
        // Add from gameObjects array
        this.gameObjects.forEach(obj => {
            if (this.shouldExportObject(obj)) {
                allObjects.add(obj);
            }
        });
        
        // Add from specific arrays (in case something's missing from gameObjects)
        this.planets.forEach(obj => allObjects.add(obj));
        this.bonuses.forEach(obj => allObjects.add(obj));
        this.textObjects.forEach(obj => allObjects.add(obj));
        this.pointingArrows.forEach(obj => allObjects.add(obj));
        
        // Add penguin if it exists
        if (this.penguin && this.shouldExportObject(this.penguin)) {
            allObjects.add(this.penguin);
        }
        
        plog.debug('Objects found in arrays:');
        plog.debug('- gameObjects:', this.gameObjects.length);
        plog.debug('- planets:', this.planets.length);
        plog.debug('- bonuses:', this.bonuses.length);
        plog.debug('- textObjects:', this.textObjects.length);
        plog.debug('- pointingArrows:', this.pointingArrows.length);
        plog.debug('- penguin:', this.penguin ? 1 : 0);
        
        return Array.from(allObjects);
    }
    
    shouldExportObject(obj) {
        // Only schema-backed runtime objects belong in a level definition.
        const type = levelObjectTypeFromClassName(obj.constructor.name);
        return type !== null && type !== LevelObjectType.PENGUIN;
    }
    
    exportObjectComprehensively(obj) {
        const className = obj.constructor.name;
        plog.debug(`Exporting ${className}:`, obj);
        
        // Start with base object data
        const type = levelObjectTypeFromClassName(className);
        if (!type) {
            plog.warn(`Skipping runtime object without a level schema type: ${className}`);
            return null;
        }
        const exportData = {
            type
        };
        
        // Export position as object (matching level JSON format)
        const coords = this.getObjectCoordinates(obj);
        if (coords) {
            exportData.position = { x: coords.x, y: coords.y };
        }
        
        // Export ALL properties under 'properties' object (matching level JSON format)
        const properties = this.extractAllProperties(obj);
        
        // Export orbit system if present
        if (obj.orbitSystem) {
            properties.orbit = this.exportOrbitSystem(obj.orbitSystem);
        }
        
        // Only add properties object if it has content
        if (Object.keys(properties).length > 0) {
            exportData.properties = properties;
        }
        
        return exportData;
    }
    
    getObjectCoordinates(obj) {
        if (typeof obj.x === 'number' && typeof obj.y === 'number') {
            return { x: obj.x, y: obj.y };
        } else if (obj.position && typeof obj.position.x === 'number' && typeof obj.position.y === 'number') {
            return { x: obj.position.x, y: obj.position.y };
        }
        return null;
    }
    
    extractAllProperties(obj) {
        const properties = {};
        const className = obj.constructor.name;
        
        // Define properties to extract for each class type
        const propertyMaps = {
            'Planet': ['radius', 'mass', 'collisionRadius', 'gravitationalReach', 'color', 'planetType'],
            'Bonus': ['value', 'rotationSpeed', 'state', 'collectedRotationSpeed'],
            'Target': ['width', 'height', 'spriteType'], // Target uses width/height, not radius
            'Slingshot': ['anchorX', 'anchorY', 'stretchLimit', 'velocityMultiplier'],
            'TextObject': ['content', 'fontSize', 'color', 'fontFamily', 'textAlign', 'backgroundColor', 'padding', 'autoSize'], // content not textContent
            'PointingArrow': ['color', 'glowColor', 'baseWidth', 'scaleWithDistance', 'minWidth', 'maxWidth', 'pulseSpeed'],
            'Penguin': ['state'] // Penguin shouldn't really be exported in levels
        };
        
        // Common GameObject properties
        const commonProps = ['id', 'name', 'rotation', 'alpha', 'visible', 'width', 'height', 'renderOrder'];
        
        // Extract class-specific properties
        const classProps = propertyMaps[className] || [];
        const allProps = [...commonProps, ...classProps];
        
        allProps.forEach(prop => {
            if (obj[prop] !== undefined && obj[prop] !== null) {
                properties[prop] = obj[prop];
            }
        });

        // Auto-sized text changes its rendered width every frame. Persist the
        // editor's configured wrap limit instead of that transient measurement.
        if (className === 'TextObject' && obj.maxWidth !== undefined) {
            properties.width = obj.maxWidth + (obj.padding * 2);
        }
        
        // Handle special nested properties
        if (className === 'PointingArrow' && obj.pointingAt) {
            properties.pointingAt = { x: obj.pointingAt.x, y: obj.pointingAt.y };
        }
        
        // Also do a greedy scan for any other properties that look important
        this.addDiscoveredProperties(obj, properties);
        
        return properties;
    }
    
    addDiscoveredProperties(obj, properties) {
        // Scan object for additional properties that might be important
        for (const key in obj) {
            if (obj.hasOwnProperty(key) && 
                !properties.hasOwnProperty(key) && 
                !this.isInternalProperty(key) &&
                obj[key] !== undefined && 
                obj[key] !== null) {
                
                const value = obj[key];
                
                // Only export simple values and avoid functions/complex objects
                if (typeof value === 'string' || 
                    typeof value === 'number' || 
                    typeof value === 'boolean') {
                    properties[key] = value;
                    plog.debug(`Discovered property ${key} = ${value}`);
                }
            }
        }
    }
    
    isInternalProperty(key) {
        // Skip internal properties that shouldn't be exported
        const internalProps = [
            'position', 'orbitSystem', 'assetLoader', 'bonusSprite', 'bonusHitSprite',
            'currentSprite', 'planet', 'canvas', 'ctx', 'sprites', 'animations'
        ];
        return internalProps.includes(key) || key.startsWith('_');
    }
    
    exportOrbitSystem(orbitSystem) {
        const exportData = {
            orbitCenter: orbitSystem.orbitCenter ? { 
                x: orbitSystem.orbitCenter.x, 
                y: orbitSystem.orbitCenter.y 
            } : null,
            orbitTargetId: orbitSystem.orbitTargetId || null,
            orbitRadius: orbitSystem.orbitRadius,
            orbitSpeed: orbitSystem.orbitSpeed,
            orbitAngle: orbitSystem.orbitAngle,
            orbitType: orbitSystem.orbitType,
            orbitParams: orbitSystem.orbitParams || {}
        };
        
        // Add gravity-specific properties if it's a gravity orbit
        if (orbitSystem.orbitType === LevelOrbitType.GRAVITY) {
            exportData.orbitParams = {
                ...exportData.orbitParams,
                gravityStrength: orbitSystem.gravityStrength ?? PHYSICS_CONFIG.orbit.gravityStrength,
                initialVelocity: orbitSystem.velocity ? { 
                    x: orbitSystem.velocity.x, 
                    y: orbitSystem.velocity.y 
                } : { ...PHYSICS_CONFIG.orbit.initialVelocity }
            };
        }
        
        return exportData;
    }
    
    exportLevelRules() {
        return {
            maxTries: this.levelRules.maxTries,
            timeLimit: this.levelRules.timeLimit,
            scoreMultiplier: this.levelRules.scoreMultiplier,
            requiredBonuses: this.levelRules.requiredBonuses,
            allowedMisses: this.levelRules.allowedMisses,
            gravitationalConstant: this.levelRules.gravitationalConstant
        };
    }


    
    createAlphaMaskAtLaunchPosition() {
        if (!this.penguin) return;
        
        // Get current trace color (matching original game's pTraceColor)
        const traceColor = this.shotColors[this.currentColorIndex];
        
        // Create alpha mask object (matching original game's k1, k2, k3 sprites)
        const alphaMask = {
            x: this.penguin.x,
            y: this.penguin.y,
            color: traceColor,
            alpha: 0.6, // Semi-transparent like original
            renderCanvas: this.getColoredAlphaMaskCanvas(traceColor)
        };
        
        // Shift existing masks (matching original game's setUpSnapping logic)
        // k3 gets k2's position, k2 gets k1's position, k1 gets current position
        if (this.alphaMasks.length >= RENDER_CONFIG.shotTrails.alphaMaskHistory) {
            this.alphaMasks[2] = this.alphaMasks[1]; // k3 = k2
            this.alphaMasks[1] = this.alphaMasks[0]; // k2 = k1
            this.alphaMasks[0] = alphaMask; // k1 = new position
        } else {
            this.alphaMasks.unshift(alphaMask);
        }
        

    }
    
    clearAlphaMasks() {
        this.alphaMasks = [];
        plog.debug('Cleared all alpha masks');
    }
    
    loadAlphaMask() {
        // Load the alpha mask image directly
        this.alphaMaskImage = new Image();
        this.alphaMaskImage.onload = () => {
            try {
                this.prepareAlphaMaskStencil();
                for (const mask of this.alphaMasks) {
                    mask.renderCanvas = this.getColoredAlphaMaskCanvas(mask.color);
                }
                plog.success('Alpha mask image loaded and cached successfully');
            } catch (error) {
                plog.error('Failed to prepare alpha mask image:', error);
            }
        };
        this.alphaMaskImage.onerror = () => {
            plog.error('Failed to load alpha mask image');
        };
        this.alphaMaskImage.src = assetPath('ui/alpha_mask.png');
    }

    prepareAlphaMaskStencil() {
        const width = this.alphaMaskImage.naturalWidth || this.alphaMaskImage.width;
        const height = this.alphaMaskImage.naturalHeight || this.alphaMaskImage.height;
        const canvas = document.createElement('canvas');
        canvas.width = width;
        canvas.height = height;
        const context = canvas.getContext('2d');
        context.drawImage(this.alphaMaskImage, 0, 0);

        const imageData = context.getImageData(0, 0, width, height);
        const pixels = imageData.data;
        for (let index = 0; index < pixels.length; index += 4) {
            const gray = (pixels[index] + pixels[index + 1] + pixels[index + 2]) / 3;
            pixels[index] = 255;
            pixels[index + 1] = 255;
            pixels[index + 2] = 255;
            pixels[index + 3] = 255 - gray;
        }
        context.putImageData(imageData, 0, 0);

        this.alphaMaskStencil = canvas;
        this.coloredAlphaMaskCanvases.clear();
    }

    getColoredAlphaMaskCanvas(color) {
        if (!this.alphaMaskStencil) return null;
        const cached = this.coloredAlphaMaskCanvases.get(color);
        if (cached) return cached;

        const canvas = document.createElement('canvas');
        canvas.width = this.alphaMaskStencil.width;
        canvas.height = this.alphaMaskStencil.height;
        const context = canvas.getContext('2d');
        context.fillStyle = color;
        context.fillRect(0, 0, canvas.width, canvas.height);
        context.globalCompositeOperation = 'destination-in';
        context.drawImage(this.alphaMaskStencil, 0, 0);
        this.coloredAlphaMaskCanvases.set(color, canvas);
        return canvas;
    }
}

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = Game;
} 

export { Game, GameState };
