import { GameState } from './gameState.js';

/**
 * Owns browser-session and campaign state. Deterministic world state is applied
 * through the simulation adapter, but its counters are stored here so there is
 * one live owner rather than a second set of fields on Game.
 */
export class GameSession {
    constructor() {
        this.state = GameState.MENU;
        this.level = 1;
        this.score = 0;
        this.currentLevelBestScore = 0;
        this.currentAttemptScore = 0;
        this.distance = 0;
        this.tries = 0;
        this.highScore = 0;
        this.planetCollisions = 0;
        this.levelRules = null;
        this.levelMetadata = {
            name: 'Custom Level 1',
            description: 'Generated by Level Editor'
        };
        this.currentRunScoreSaved = false;
        this.lastScoreImprovement = 0;
    }

    setState(nextState) {
        const previousState = this.state;
        this.state = nextState;
        return { changed: previousState !== nextState, previousState, nextState };
    }

    startCampaign() {
        this.level = 1;
        this.score = 0;
        this.currentLevelBestScore = 0;
        this.currentRunScoreSaved = false;
        this.resetLevelCounters();
    }

    beginLevel(level = this.level) {
        this.level = level;
        this.currentLevelBestScore = 0;
        this.resetLevelCounters();
    }

    advanceLevel() {
        this.beginLevel(Number(this.level) + 1);
        return this.level;
    }

    resetLevelCounters() {
        this.tries = 0;
        this.distance = 0;
        this.currentAttemptScore = 0;
        this.planetCollisions = 0;
    }

    resetAttemptCounters() {
        this.distance = 0;
        this.currentAttemptScore = 0;
    }

    applyLevelScore(result) {
        this.currentLevelBestScore = result.levelContribution;
        this.score = result.totalScore;
        this.lastScoreImprovement = result.scoreImprovement;
    }

    setLevelMetadata(metadata = {}) {
        this.levelMetadata = {
            name: metadata.name || `Custom Level ${this.level}`,
            description: metadata.description ?? '',
            ...(metadata.saveId !== undefined ? { saveId: metadata.saveId } : {}),
            ...(metadata.catalogReference ? { catalogReference: metadata.catalogReference } : {})
        };
        return this.levelMetadata;
    }
}

export default GameSession;
