import { readFile, writeFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { resolve } from 'node:path';
import process from 'node:process';
import { pathToFileURL } from 'node:url';

const ROOT = new URL('../', import.meta.url);
const readJson = async path => JSON.parse(await readFile(new URL(path, ROOT), 'utf8'));
const stableJson = value => `${JSON.stringify(value, null, 2)}\n`;
const banner = source => `// Generated by tools/generateDomainContracts.js from ${source}. Do not edit.\n\n`;

function formatRust(content) {
    const candidates = [process.env.RUSTFMT, process.env.USERPROFILE ? `${process.env.USERPROFILE}/.cargo/bin/rustfmt.exe` : null, 'rustfmt'].filter(Boolean);
    let result;
    for (const executable of candidates) {
        result = spawnSync(executable, ['--edition', '2024'], { input: content, encoding: 'utf8' });
        if (!result.error || result.error.code !== 'ENOENT') break;
    }
    if (result?.error) throw new Error(`rustfmt is required to generate Rust contracts: ${result.error.message}`);
    if (result.status !== 0) throw new Error(`rustfmt rejected generated contracts:\n${result.stderr}`);
    return result.stdout;
}

function constantName(value) {
    return value.replace(/([a-z0-9])([A-Z])/g, '$1_$2').replace(/[^a-zA-Z0-9]+/g, '_').toUpperCase();
}

function pascalCase(value) {
    return value.split(/[^a-zA-Z0-9]+/).filter(Boolean)
        .map(part => part[0].toUpperCase() + part.slice(1)).join('');
}

function snakeCase(value) {
    return value.replace(/([a-z0-9])([A-Z])/g, '$1_$2').replace(/[^a-zA-Z0-9]+/g, '_').toLowerCase();
}

/** Validate the declarative projection from authored gameplay objects to normalized simulation records. */
export function validateGameplaySimulationProjections(objectSchema, simulationSchema) {
    const objects = objectSchema['x-spaced-penguin-objects'];
    if (!Array.isArray(objects)) throw new Error('Game object schema is missing x-spaced-penguin-objects');
    for (const object of objects.filter(candidate => candidate.capabilities?.gameplay === true)) {
        const projection = object['x-spaced-penguin-simulation-projection'];
        if (!projection || typeof projection.record !== 'string' || !projection.fields || typeof projection.fields !== 'object') {
            throw new Error(`${object.className} gameplay object requires x-spaced-penguin-simulation-projection metadata`);
        }
        const definition = simulationSchema.$defs?.[projection.record];
        if (!definition || definition.type !== 'object') throw new Error(`${object.className} simulation projection references missing record ${projection.record}`);
        const properties = object.properties || {};
        const targetProperties = definition.properties || {};
        const fields = projection.fields;
        for (const field of Object.keys(properties)) {
            const mapping = fields[field];
            if (!mapping) throw new Error(`${object.className} gameplay field ${field} has no simulation projection mapping`);
            const excluded = typeof mapping === 'object' && Object.hasOwn(mapping, 'excluded');
            const target = typeof mapping === 'string' ? mapping : mapping?.field;
            if (excluded) {
                if (typeof mapping.excluded !== 'string' || !mapping.excluded.trim()) throw new Error(`${object.className}.${field} simulation projection exclusion requires a reason`);
            } else {
                if (typeof target !== 'string' || !targetProperties[target]) throw new Error(`${object.className}.${field} simulation projection references missing ${projection.record}.${target}`);
                if (target !== field && (typeof mapping !== 'object' || typeof mapping.reason !== 'string' || !mapping.reason.trim())) {
                    throw new Error(`${object.className}.${field} normalized simulation mapping requires a reason`);
                }
            }
        }
        for (const field of Object.keys(fields)) {
            if (!Object.hasOwn(properties, field)) throw new Error(`${object.className} simulation projection contains unknown authored field ${field}`);
        }
    }
    return true;
}

function editorProperty(key, schema) {
    const editor = schema['x-editor'];
    if (!editor) return null;
    return {
        key,
        label: editor.label || key,
        type: editor.control || (schema.type === 'boolean' ? 'checkbox' : schema.enum ? 'select' : schema.type),
        ...('min' in editor ? { min: editor.min } : {}),
        ...('max' in editor ? { max: editor.max } : {}),
        ...('step' in editor ? { step: editor.step } : {}),
        ...(editor.optionsFrom ? { optionsFrom: editor.optionsFrom } : {}),
        ...(schema.enum ? { options: schema.enum } : {})
    };
}

function objectContract(object) {
    const defaults = Object.fromEntries(Object.entries(object.properties || {})
        .filter(([, schema]) => Object.hasOwn(schema, 'default'))
        .map(([key, schema]) => [key, schema.default]));
    const properties = [
        ...(object.editorFields || []),
        ...Object.entries(object.properties || {}).map(([key, schema]) => editorProperty(key, schema)).filter(Boolean)
    ];
    return {
        className: object.className,
        type: object.type,
        label: object.label,
        aliases: object.aliases || [],
        collections: object.collections || [],
        singleton: object.singleton || null,
        levelRole: object.levelRole || null,
        relationshipValidator: object.relationshipValidator || null,
        physicsAdd: object.physics?.add || null,
        physicsRemove: object.physics?.remove || null,
        defaults,
        properties,
        serializedProperties: object.serializedProperties || [],
        capabilities: object.capabilities || {}
    };
}

function levelDefaultsForObject(object) {
    const metadata = object['x-spaced-penguin-level-defaults'];
    if (!metadata) return null;
    if (typeof metadata.key !== 'string' || metadata.key.length === 0) {
        throw new Error(`${object.className} level defaults require a non-empty key`);
    }
    const properties = object.properties || {};
    const include = metadata.include || [];
    const defaults = Object.fromEntries(include.map(key => {
        const property = properties[key];
        if (!property || !Object.hasOwn(property, 'default')) {
            throw new Error(`${object.className} level defaults include ${key}, but it has no schema default`);
        }
        return [key, structuredClone(property.default)];
    }));
    for (const key of Object.keys(metadata.derived || {})) {
        if (Object.hasOwn(defaults, key)) {
            throw new Error(`${object.className} level defaults derive an already included property: ${key}`);
        }
    }
    return { key: metadata.key, defaults: { ...defaults, ...structuredClone(metadata.derived || {}) } };
}

function levelDefaultsForSchema(objectSchema, levelSchema) {
    const defaults = {};
    for (const object of objectSchema['x-spaced-penguin-objects']) {
        const view = levelDefaultsForObject(object);
        if (!view) continue;
        if (Object.hasOwn(defaults, view.key)) {
            throw new Error(`Duplicate LEVEL_DEFAULTS key: ${view.key}`);
        }
        defaults[view.key] = view.defaults;
    }

    const rules = levelSchema['x-spaced-penguin-level-defaults']?.rules || [];
    if (rules.length) {
        const rulesSchema = levelSchema.$defs?.Rules?.properties || {};
        defaults.rules = Object.fromEntries(rules.map(key => {
            const property = rulesSchema[key];
            if (!property || !Object.hasOwn(property, 'default')) {
                throw new Error(`LEVEL_DEFAULTS rules include ${key}, but it has no schema default`);
            }
            return [key, structuredClone(property.default)];
        }));
    }
    return defaults;
}

function generateGameObjectJs(schema, levelSchema) {
    const objects = schema['x-spaced-penguin-objects'];
    const types = Object.fromEntries(objects.map(object => [object.constantName || constantName(object.className), object.type]));
    const aliases = Object.fromEntries(objects.flatMap(object => (object.aliases || []).map(alias => [alias.toLowerCase(), object.type]))
        .filter(([alias, type]) => alias !== type));
    const contracts = Object.fromEntries(objects.map(object => [object.className, objectContract(object)]));
    const levelDefaults = levelDefaultsForSchema(schema, levelSchema);
    return `${banner('domain/gameObjects.schema.json + domain/level.schema.json')}` +
        `export const LevelObjectType = Object.freeze(${JSON.stringify(types, null, 4)});\n\n` +
        `export const LEVEL_OBJECT_TYPE_ALIASES = Object.freeze(${JSON.stringify(aliases, null, 4)});\n\n` +
        `export const GAME_OBJECT_CONTRACTS = Object.freeze(${JSON.stringify(contracts, null, 4)});\n\n` +
        `export const LEVEL_OBJECT_TYPES = Object.freeze(Object.values(LevelObjectType));\n` +
        `export const LEVEL_OBJECT_TYPE_NAMES = Object.freeze([...LEVEL_OBJECT_TYPES, ...Object.keys(LEVEL_OBJECT_TYPE_ALIASES)]);\n` +
        `export const LEVEL_OBJECT_TYPE_BY_CLASS_NAME = Object.freeze(Object.fromEntries(Object.values(GAME_OBJECT_CONTRACTS).map(contract => [contract.className, contract.type])));\n\n` +
        `function freezeLevelDefaults(value) {\n` +
        `    if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value;\n` +
        `    for (const child of Object.values(value)) freezeLevelDefaults(child);\n` +
        `    return Object.freeze(value);\n` +
        `}\n\n` +
        `export const LEVEL_DEFAULTS = freezeLevelDefaults(${JSON.stringify(levelDefaults, null, 4)});\n\n` +
        `export function normalizeLevelObjectType(type) {\n` +
        `    if (typeof type !== 'string') return null;\n` +
        `    const normalized = type.trim().toLowerCase();\n` +
        `    return LEVEL_OBJECT_TYPE_ALIASES[normalized] || normalized;\n` +
        `}\n`;
}

function eventDefinitions(simulationSchema) {
    return simulationSchema.$defs.SimulationEvent.oneOf.map(variant => ({
        type: variant.properties.type.const,
        fields: Object.keys(variant.properties).filter(key => key !== 'type'),
        required: variant.required.filter(key => key !== 'type')
    }));
}

function generateSimulationJs(schema) {
    const events = eventDefinitions(schema);
    const types = Object.fromEntries(events.map(event => [constantName(event.type), event.type]));
    const shapes = Object.fromEntries(events.map(event => [event.type, { fields: event.fields, required: event.required }]));
    const outputShapes = Object.fromEntries(['StepPatch', 'PenguinPatch', 'CounterPatch', 'TrajectoryPoint', 'TrajectoryResult'].map(name => {
        const definition = schema.$defs[name];
        return [name, { fields: Object.keys(definition.properties || {}), required: definition.required || [] }];
    }));
    return `${banner('domain/simulation.schema.json')}` +
        `export const SimulationEventType = Object.freeze(${JSON.stringify(types, null, 4)});\n\n` +
        `export const SIMULATION_EVENT_SHAPES = Object.freeze(${JSON.stringify(shapes, null, 4)});\n\n` +
        `export const SIMULATION_OUTPUT_SHAPES = Object.freeze(${JSON.stringify(outputShapes, null, 4)});\n\n` +
        `export function isSimulationEvent(value) {\n` +
        `    if (!value || typeof value !== 'object') return false;\n` +
        `    const shape = SIMULATION_EVENT_SHAPES[value.type];\n` +
        `    return Boolean(shape && shape.required.every(field => Object.hasOwn(value, field)));\n` +
        `}\n`;
}

function referencedDefinition(property) {
    return property.$ref?.split('/').at(-1) || property.items?.$ref?.split('/').at(-1) || null;
}

function wirePrimitive(property) {
    if (property.$ref) return 'record';
    const types = Array.isArray(property.type) ? property.type : [property.type];
    const nullable = types.includes('null');
    const base = types.find(type => type !== 'null');
    if (base === 'array' && (property.items?.oneOf || property.items?.$ref?.endsWith('/SimulationEvent'))) return 'eventArray';
    if (base === 'array' && property.items?.$ref) return 'recordArray';
    if (base === 'array' && property.items?.type === 'boolean') return 'boolArray';
    if (base === 'array' && property.items?.type === 'string') return 'stringArray';
    if (base === 'number') return nullable ? 'optionalF64' : 'f64';
    if (base === 'integer') return nullable ? 'optionalCount' : 'count';
    if (base === 'boolean' && !nullable) return 'u8';
    if (base === 'string') return nullable ? 'optionalString' : 'string';
    return null;
}

function wireSection(schema, section = 'input') {
    const wire = schema['x-spaced-penguin-wire'];
    if (section === 'input') return wire;
    if (!wire?.output) throw new Error('Simulation output wire declaration is missing');
    return { ...wire, ...wire.output, version: wire.output.version || wire.version };
}

function eventWireDefinition(schema, wire) {
    const declaration = wire.event;
    if (!declaration) return null;
    const definition = schema.$defs?.[declaration.definition];
    if (!definition?.oneOf || declaration.tagCodec !== 'u8' || !Array.isArray(declaration.variants)) {
        throw new Error('Simulation event wire declaration requires a oneOf definition, u8 tagCodec, and variants');
    }
    const expected = eventDefinitions(schema);
    if (declaration.variants.length !== expected.length) throw new Error('Simulation event wire variants must cover the union exactly once');
    const seen = new Set();
    for (let index = 0; index < declaration.variants.length; index += 1) {
        const variant = declaration.variants[index];
        if (variant.type !== expected[index].type || variant.tag !== index || seen.has(variant.type)) {
            throw new Error(`Simulation event wire variant ${index} must preserve schema order with a unique tag`);
        }
        seen.add(variant.type);
    }
    return expected.map((event, index) => ({ ...event, tag: declaration.variants[index].tag }));
}

function canonicalWireLayout(schema, section) {
    const wire = wireSection(schema, section);
    const records = Object.entries(wire.records || {}).map(([name, layout]) => [name, layout.map(entry => {
        const property = schema.$defs[name]?.properties?.[entry.field] || {};
        return {
            field: entry.field,
            codec: Object.hasOwn(entry, 'excluded') ? 'excluded' : wirePrimitive(property),
            reference: referencedDefinition(property),
            ...(Object.hasOwn(entry, 'excluded') ? { reason: entry.excluded } : {})
        };
    })]);
    const events = eventWireDefinition(schema, wire);
    return { section, name: wire.name, version: wire.version, endianness: wire.endianness, encoding: wire.encoding, magic: wire.magic, root: wire.root, roots: wire.roots || [wire.root], records,
        ...(events ? { event: events.map(({ type, fields, required, tag }) => ({ type, tag, fields: fields.map(field => ({ field, codec: wirePrimitive(schema.$defs.SimulationEvent.oneOf.find(variant => variant.properties.type.const === type).properties[field]), required: required.includes(field) })) })) } : {}) };
}

export function computeSimulationWireFingerprint(schema, section = 'input') {
    const canonical = JSON.stringify(canonicalWireLayout(schema, section));
    return `sha256:${createHash('sha256').update(canonical).digest('hex')}`;
}

export function validateSimulationWireLayout(schema, section = 'input', { checkFingerprint = true } = {}) {
    const wire = wireSection(schema, section);
    if (!wire || !Number.isInteger(wire.version) || wire.version < 1) throw new Error('Simulation wire requires a positive integer version');
    if (wire.endianness !== 'little') throw new Error('Simulation wire generator only supports little endian layouts');
    if (typeof wire.magic !== 'string' || !/^0x[0-9a-f]{8}$/i.test(wire.magic)) throw new Error('Simulation wire requires an eight-digit hexadecimal magic value');
    if (!schema.$defs?.[wire.root]) throw new Error(`Simulation wire root definition is missing: ${wire.root}`);
    const eventWire = eventWireDefinition(schema, wire);

    const reachable = new Set();
    const roots = Array.isArray(wire.roots) ? wire.roots : [wire.root];
    const pending = [...roots];
    while (pending.length) {
        const name = pending.shift();
        if (reachable.has(name)) continue;
        reachable.add(name);
        const definition = schema.$defs[name];
        const layout = wire.records?.[name];
        if (!definition || definition.type !== 'object') {
            if (definition?.oneOf && (definition['x-spaced-penguin-rust']?.name === 'SimulationEvent' || name === 'SimulationEvent')) continue;
            throw new Error(`Simulation wire record ${name} must reference an object definition`);
        }
        if (!Array.isArray(layout)) throw new Error(`Simulation wire layout is missing record ${name}`);
        const properties = definition.properties || {};
        const seen = new Set();
        for (const entry of layout) {
            if (!entry || typeof entry.field !== 'string' || !Object.hasOwn(properties, entry.field)) throw new Error(`Simulation wire record ${name} contains unknown field ${entry?.field}`);
            if (seen.has(entry.field)) throw new Error(`Simulation wire record ${name} repeats field ${entry.field}`);
            seen.add(entry.field);
            if (Object.hasOwn(entry, 'excluded')) {
                if (typeof entry.excluded !== 'string' || !entry.excluded.trim()) throw new Error(`Simulation wire exclusion ${name}.${entry.field} requires a reason`);
                continue;
            }
            const primitive = wirePrimitive(properties[entry.field]);
            if (!primitive) throw new Error(`Simulation wire field ${name}.${entry.field} has no supported codec or exclusion`);
            if (primitive === 'eventArray' && !eventWire) throw new Error(`Simulation ${section} wire event array ${name}.${entry.field} requires an event declaration`);
            const reference = referencedDefinition(properties[entry.field]);
            if (reference && schema.$defs[reference]?.type === 'object') pending.push(reference);
        }
        for (const field of Object.keys(properties)) {
            if (!seen.has(field)) throw new Error(`Simulation wire layout does not cover ${name}.${field}`);
        }
    }
    for (const name of Object.keys(wire.records || {})) {
        if (!reachable.has(name)) throw new Error(`Simulation wire record ${name} is not reachable from ${roots.join(', ')}`);
    }
    if (checkFingerprint) {
        const expected = schema['x-spaced-penguin-wire']?.fingerprints?.[section];
        if (typeof expected !== 'string' || !expected.startsWith('sha256:')) throw new Error(`Simulation ${section} wire requires a schema fingerprint`);
        const actual = computeSimulationWireFingerprint(schema, section);
        if (expected !== actual) throw new Error(`Simulation ${section} wire fingerprint mismatch: schema has ${expected}, computed ${actual}; update the wire version/fingerprint intentionally`);
    }
    return wire;
}

function jsWireWrite(name, field, property) {
    const value = `value.${field}`;
    const codec = wirePrimitive(property);
    if (codec === 'record') return `    write${referencedDefinition(property)}(writer, ${value});`;
    if (codec === 'recordArray') {
        const itemName = referencedDefinition(property);
        const source = Object.hasOwn(property, 'default') ? `(${value} ?? ${JSON.stringify(property.default)})` : value;
        return `    writer.u32(${source}.length);\n    for (const item of ${source}) write${itemName}(writer, item);`;
    }
    if (codec === 'eventArray' || codec === 'boolArray' || codec === 'stringArray') {
        const source = Object.hasOwn(property, 'default') ? `(${value} ?? ${JSON.stringify(property.default)})` : value;
        const itemWriter = codec === 'eventArray' ? 'writeSimulationEvent(writer, item)' : codec === 'boolArray' ? 'writer.u8(item)' : 'writer.string(item)';
        return `    writer.u32(${source}.length);\n    for (const item of ${source}) ${itemWriter};`;
    }
    const method = codec === 'count' ? 'f64' : codec;
    return `    writer.${method}(${value});`;
}

function jsWireRead(property) {
    const codec = wirePrimitive(property);
    if (codec === 'record') return `this.read${referencedDefinition(property)}()`;
    if (codec === 'recordArray') {
        const itemName = referencedDefinition(property);
        return `this.array(() => this.read${itemName}())`;
    }
    if (codec === 'eventArray') return 'this.array(() => this.readSimulationEvent())';
    if (codec === 'boolArray') return 'this.array(() => this.u8())';
    if (codec === 'stringArray') return 'this.array(() => this.string())';
    return `this.${codec === 'count' ? 'count' : codec}()`;
}

function outputReadFunctions(schema, wire) {
    const names = Object.keys(wire.records).filter(name => schema.$defs[name]?.type === 'object');
    return names.map(name => {
        const definition = schema.$defs[name];
        const fields = wire.records[name].filter(entry => !Object.hasOwn(entry, 'excluded')).map(entry => `        ${JSON.stringify(entry.field)}: ${jsWireRead(definition.properties[entry.field])}`).join(',\n');
        return `    read${name}() { return {\n${fields}\n        }; }`;
    }).join('\n');
}

function jsEventWriteField(property, value) {
    const codec = wirePrimitive(property);
    if (codec === 'record') return `write${referencedDefinition(property)}(writer, ${value});`;
    if (codec === 'count') return `writer.f64(${value});`;
    return `writer.${codec}(${value});`;
}

function jsEventReadField(property) {
    const codec = wirePrimitive(property);
    if (codec === 'record') return `this.read${referencedDefinition(property)}()`;
    return `this.${codec === 'count' ? 'count' : codec}()`;
}

function generateJsEventCodec(schema, wire) {
    const events = eventWireDefinition(schema, wire);
    if (!events) return '';
    const variants = schema.$defs.SimulationEvent.oneOf;
    const writes = events.map((event, index) => {
        const variant = variants[index];
        const required = new Set(event.required);
        const lines = [`        writer.tag(${event.tag});`];
        for (const field of event.fields) {
            const property = variant.properties[field];
            const value = `value.${field}`;
            if (!required.has(field)) lines.push(`        writer.u8(${value} == null ? 0 : 1);`, `        if (${value} != null) ${jsEventWriteField(property, value)}`);
            else lines.push(`        ${jsEventWriteField(property, value)}`);
        }
        return `    case ${JSON.stringify(event.type)}:\n${lines.join('\n')}\n        return;`;
    }).join('\n');
    const reads = events.map((event, index) => {
        const variant = variants[index];
        const required = new Set(event.required);
        const fields = event.fields.map(field => {
            const property = variant.properties[field];
            const decoded = jsEventReadField(property);
            const value = required.has(field) ? decoded : `(this.u8() ? ${decoded} : null)`;
            return `            ${JSON.stringify(field)}: ${value}`;
        }).join(',\n');
        return `        case ${event.tag}: return {\n            type: ${JSON.stringify(event.type)},\n${fields}\n        };`;
    }).join('\n');
    return `function writeSimulationEvent(writer, value) {\n    if (!value || typeof value.type !== 'string') throw new Error('simulation event requires a type');\n    switch (value.type) {\n${writes}\n    default: throw new Error('unknown simulation event type: ' + value.type);\n    }\n}`;
}

function generateJsEventReader(schema, wire) {
    const events = eventWireDefinition(schema, wire);
    if (!events) return '    readSimulationEvent() { throw new Error(\'simulation event wire declaration is missing\'); }';
    const variants = schema.$defs.SimulationEvent.oneOf;
    const reads = events.map((event, index) => {
        const variant = variants[index];
        const required = new Set(event.required);
        const fields = event.fields.map(field => {
            const decoded = jsEventReadField(variant.properties[field]);
            return `            ${JSON.stringify(field)}: ${required.has(field) ? decoded : `(this.u8() ? ${decoded} : null)`}`;
        }).join(',\n');
        return `        case ${event.tag}: return {\n            type: ${JSON.stringify(event.type)},\n${fields}\n        };`;
    }).join('\n');
    return `    readSimulationEvent() {\n        const tag = this.u8Tag();\n        switch (tag) {\n${reads}\n        default: throw new Error('unknown simulation event tag: ' + tag);\n        }\n    }`;
}

function generateSimulationWireJs(schema) {
    const wire = validateSimulationWireLayout(schema, 'input');
    const output = validateSimulationWireLayout(schema, 'output');
    const records = Object.entries(wire.records).map(([name, layout]) => {
        const properties = schema.$defs[name].properties;
        const body = layout.filter(entry => !Object.hasOwn(entry, 'excluded')).map(entry => jsWireWrite(name, entry.field, properties[entry.field])).join('\n');
        return `function write${name}(writer, value) {\n${body}\n}`;
    }).join('\n\n');
    const outputRecords = Object.entries(output.records).filter(([name]) => !Object.hasOwn(wire.records, name)).map(([name, layout]) => {
        const properties = schema.$defs[name].properties;
        const body = layout.filter(entry => !Object.hasOwn(entry, 'excluded')).map(entry => jsWireWrite(name, entry.field, properties[entry.field])).join('\n');
        return `function write${name}(writer, value) {\n${body}\n}`;
    }).join('\n\n');
    return `${banner('domain/simulation.schema.json x-spaced-penguin-wire')}const encoder = new TextEncoder();
const decoder = new TextDecoder();
const MAGIC = ${wire.magic};
export const SIMULATION_WIRE_VERSION = ${wire.version};
export const SIMULATION_OUTPUT_WIRE_VERSION = ${output.version};

class Writer {
    constructor(capacity = 4096) { this.bytes = new Uint8Array(capacity); this.view = new DataView(this.bytes.buffer); this.offset = 0; }
    reserve(length) { if (this.offset + length <= this.bytes.length) return; let size = this.bytes.length; while (size < this.offset + length) size *= 2; const next = new Uint8Array(size); next.set(this.bytes); this.bytes = next; this.view = new DataView(next.buffer); }
    u8(value) { this.reserve(1); this.view.setUint8(this.offset, value ? 1 : 0); this.offset += 1; }
    tag(value) { this.reserve(1); this.view.setUint8(this.offset, value); this.offset += 1; }
    u32(value) { this.reserve(4); this.view.setUint32(this.offset, value >>> 0, true); this.offset += 4; }
    f64(value) { this.reserve(8); this.view.setFloat64(this.offset, value, true); this.offset += 8; }
    string(value) { const bytes = encoder.encode(value); this.u32(bytes.length); this.reserve(bytes.length); this.bytes.set(bytes, this.offset); this.offset += bytes.length; }
    optionalString(value) { if (value == null) { this.u32(0xffffffff); return; } this.string(value); }
    optionalF64(value) { this.f64(value == null ? Number.NaN : value); }
    optionalCount(value) { this.f64(value == null ? -1 : value); }
    finish() { return this.bytes.slice(0, this.offset); }
}

${records}

${generateJsEventCodec(schema, output)}

${outputRecords}

class Reader {
    constructor(bytes) { this.bytes = bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes); this.view = new DataView(this.bytes.buffer, this.bytes.byteOffset, this.bytes.byteLength); this.offset = 0; }
    take(length) { if (!Number.isSafeInteger(length) || length < 0 || this.offset + length > this.bytes.byteLength) throw new Error('truncated simulation wire output'); const value = this.bytes.subarray(this.offset, this.offset + length); this.offset += length; return value; }
    u8() { return this.take(1)[0] !== 0; }
    u8Tag() { return this.take(1)[0]; }
    u32() { const bytes = this.take(4); return new DataView(bytes.buffer, bytes.byteOffset, 4).getUint32(0, true); }
    f64() { const bytes = this.take(8); return new DataView(bytes.buffer, bytes.byteOffset, 8).getFloat64(0, true); }
    string() { const length = this.u32(); if (length === 0xffffffff) throw new Error('required simulation wire output string is null'); return decoder.decode(this.take(length)); }
    optionalString() { const length = this.u32(); return length === 0xffffffff ? null : decoder.decode(this.take(length)); }
    optionalF64() { const value = this.f64(); return Number.isNaN(value) ? null : value; }
    count() { const value = this.f64(); if (!Number.isSafeInteger(value) || value < 0) throw new Error('invalid simulation wire output count'); return value; }
    optionalCount() { const value = this.f64(); if (value === -1) return null; if (!Number.isSafeInteger(value) || value < 0) throw new Error('invalid optional simulation wire output count'); return value; }
    array(reader) { const length = this.u32(); if (length > 0x1000000) throw new Error('simulation wire output array is too large'); return Array.from({ length }, reader); }
${generateJsEventReader(schema, output)}
${outputReadFunctions(schema, output)}
}

export function encodeSimulationStepInput(state, simulation) {
    const writer = new Writer();
    writer.u32(MAGIC);
    writer.u32(SIMULATION_WIRE_VERSION);
    write${wire.root}(writer, { state, simulation });
    return writer.finish();
}

export function encodeSimulationStepPatch(patch) {
    const writer = new Writer();
    writer.u32(MAGIC);
    writer.u32(SIMULATION_OUTPUT_WIRE_VERSION);
    writeStepPatch(writer, patch);
    return writer.finish();
}

export function decodeSimulationStepPatch(bytes) {
    const reader = new Reader(bytes);
    if (reader.u32() !== MAGIC) throw new Error('invalid simulation output wire magic');
    if (reader.u32() !== SIMULATION_OUTPUT_WIRE_VERSION) throw new Error('unsupported simulation output wire version');
    const patch = reader.readStepPatch();
    if (reader.offset !== reader.bytes.byteLength) throw new Error('trailing simulation output wire bytes');
    return patch;
}
`;
}

function expandLevelSchema(levelSchema, gameObjectSchema) {
    const schema = structuredClone(levelSchema);
    const objects = gameObjectSchema['x-spaced-penguin-objects'];
    schema.$defs.GameObject.oneOf = objects.filter(object => object.capabilities.editable).map(object => {
        const aliases = (object.aliases || []).filter(alias => alias.toLowerCase() !== object.type);
        const properties = structuredClone(object.properties || {});
        properties.orbit = { '$ref': '#/$defs/Orbit' };
        properties.waypointPath = { '$ref': '#/$defs/WaypointPath' };
        return {
            type: 'object',
            additionalProperties: true,
            required: ['type'],
            properties: {
                type: { enum: [object.type, ...aliases] },
                position: { '$ref': '#/$defs/Point' },
                properties: { type: 'object', additionalProperties: true, properties }
            }
        };
    });
    delete schema.$defs.GameObject.properties;
    return schema;
}

function generateLevelJs(schema) {
    return `${banner('domain/level.schema.json + domain/gameObjects.schema.json')}` +
        `export const LEVEL_DOCUMENT_JSON_SCHEMA = Object.freeze(${JSON.stringify(schema, null, 4)});\n`;
}

function rustType(schema, required, definitions = {}) {
    let type;
    if (schema.$ref) {
        const name = schema.$ref.split('/').at(-1);
        type = definitions[name]?.['x-spaced-penguin-rust']?.name || name;
    }
    else if (schema.oneOf) type = definitions.SimulationEvent?.['x-spaced-penguin-rust']?.name || 'SimulationEvent';
    else {
        const types = Array.isArray(schema.type) ? schema.type : [schema.type];
        const nullable = types.includes('null');
        const base = types.find(candidate => candidate !== 'null');
        if (base === 'number') type = 'f64';
        else if (base === 'integer') type = 'usize';
        else if (base === 'boolean') type = 'bool';
        else if (base === 'string') type = 'String';
        else if (base === 'array') type = `Vec<${rustType(schema.items || {}, true, definitions)}>`;
        else type = 'serde_json::Value';
        if (nullable) type = `Option<${type}>`;
    }
    if (!required && !Object.hasOwn(schema, 'default') && !type.startsWith('Option<')) type = `Option<${type}>`;
    return type;
}

function serdeDefault(schema, rustTypeName) {
    if (!Object.hasOwn(schema, 'default')) return null;
    if (schema.default === true) return 'default_true';
    if (schema.default === 1 && rustTypeName === 'f64') return 'default_one';
    return 'default';
}

function rustStruct(name, schema, definitions) {
    const meta = schema['x-spaced-penguin-rust'];
    const rustName = meta.name || name;
    const include = meta.include || Object.keys(schema.properties || {});
    const required = new Set(schema.required || []);
    const lines = [`#[derive(${meta.derive.join(', ')})]`, '#[serde(rename_all = "camelCase")]', `pub(crate) struct ${rustName} {`];
    for (const field of include) {
        const property = schema.properties[field];
        const type = rustType(property, required.has(field), definitions);
        const defaultKind = serdeDefault(property, type);
        if (defaultKind === 'default') lines.push('    #[serde(default)]');
        else if (defaultKind) lines.push(`    #[serde(default = "${defaultKind}")]`);
        lines.push(`    pub(crate) ${snakeCase(field)}: ${type},`);
    }
    lines.push('}');
    return lines.join('\n');
}

function generateRustModule(schema, module) {
    const definitions = Object.entries(schema.$defs).filter(([, definition]) => definition['x-spaced-penguin-rust']?.module === module && definition.type === 'object');
    const imports = module === 'game_objects'
        ? 'use serde::{Deserialize, Serialize};'
        : module === 'simulation_output'
            ? 'use serde::Serialize;\nuse crate::generated_game_objects::*;\nuse crate::generated_simulation_events::SimulationEvent;'
            : 'use serde::Deserialize;\nuse crate::generated_game_objects::*;';
    const helpers = module === 'game_objects'
        ? '\n\npub(crate) fn default_true() -> bool { true }\npub(crate) fn default_one() -> f64 { 1.0 }'
        : '';
    return `${banner('domain/simulation.schema.json')}${imports}\n\n${definitions.map(([name, definition]) => rustStruct(name, definition, schema.$defs)).join('\n\n')}${helpers}\n`;
}

function generateRustEvents(schema) {
    const variants = schema.$defs.SimulationEvent.oneOf.map(variant => {
        const type = variant.properties.type.const;
        const required = new Set(variant.required || []);
        const fields = Object.entries(variant.properties).filter(([name]) => name !== 'type');
        if (!fields.length) return `    ${pascalCase(type)},`;
        const body = fields.map(([name, property]) => `        ${snakeCase(name)}: ${rustType(property, required.has(name))},`).join('\n');
        return `    ${pascalCase(type)} {\n${body}\n    },`;
    }).join('\n');
    return `${banner('domain/simulation.schema.json')}use serde::{Deserialize, Serialize};\nuse crate::generated_game_objects::Point;\n\n` +
        `#[derive(Clone, Debug, Deserialize, Serialize)]\n#[serde(tag = "type", rename_all = "snake_case", rename_all_fields = "camelCase")]\n` +
        `pub(crate) enum SimulationEvent {\n${variants}\n}\n`;
}

function rustWireDefault(property) {
    if (!Object.hasOwn(property, 'default')) throw new Error('Excluded Rust wire fields must have a schema default');
    if (Array.isArray(property.default) && property.default.length === 0) return 'Vec::new()';
    if (property.default === null) return 'None';
    if (property.default === false) return 'false';
    if (property.default === true) return 'true';
    if (typeof property.default === 'number') return `${property.default}.0`;
    if (typeof property.default === 'string') return `${JSON.stringify(property.default)}.to_owned()`;
    throw new Error(`Unsupported excluded Rust wire default: ${JSON.stringify(property.default)}`);
}

function rustWireRead(property) {
    const codec = wirePrimitive(property);
    if (codec === 'record') return `self.${snakeCase(referencedDefinition(property))}()?`;
    if (codec === 'recordArray') {
        const method = snakeCase(referencedDefinition(property));
        return `{ let length = self.u32()? as usize; let mut values = Vec::with_capacity(length); for _ in 0..length { values.push(self.${method}()?); } values }`;
    }
    return `self.${snakeCase(codec)}()?`;
}

function generateSimulationWireRust(schema) {
    const wire = validateSimulationWireLayout(schema);
    const readers = Object.entries(wire.records).map(([name, layout]) => {
        const definition = schema.$defs[name];
        const meta = definition['x-spaced-penguin-rust'];
        if (!meta) throw new Error(`Simulation wire record ${name} requires x-spaced-penguin-rust metadata`);
        const included = new Set(meta.include || Object.keys(definition.properties));
        const fields = [];
        for (const entry of layout) {
            const property = definition.properties[entry.field];
            if (Object.hasOwn(entry, 'excluded')) {
                if (included.has(entry.field)) fields.push(`            ${snakeCase(entry.field)}: ${rustWireDefault(property)},`);
            } else {
                if (!included.has(entry.field)) throw new Error(`Encoded wire field ${name}.${entry.field} is omitted from its generated Rust struct`);
                fields.push(`            ${snakeCase(entry.field)}: ${rustWireRead(property)},`);
            }
        }
        const rustName = meta.name || name;
        return `    fn ${snakeCase(name)}(&mut self) -> Result<${rustName}, String> {\n        Ok(${rustName} {\n${fields.join('\n')}\n        })\n    }`;
    }).join('\n\n');
    return `${banner('domain/simulation.schema.json x-spaced-penguin-wire')}use crate::generated_game_objects::*;
use crate::generated_simulation_state::*;

const MAGIC: u32 = ${wire.magic};
const VERSION: u32 = ${wire.version};

struct Reader<'a> { bytes: &'a [u8], offset: usize }

impl<'a> Reader<'a> {
    fn take(&mut self, length: usize) -> Result<&'a [u8], String> { let end = self.offset.checked_add(length).ok_or("wire offset overflow")?; let value = self.bytes.get(self.offset..end).ok_or("truncated simulation wire input")?; self.offset = end; Ok(value) }
    fn u8(&mut self) -> Result<bool, String> { Ok(self.take(1)?[0] != 0) }
    fn u32(&mut self) -> Result<u32, String> { Ok(u32::from_le_bytes(self.take(4)?.try_into().unwrap())) }
    fn f64(&mut self) -> Result<f64, String> { Ok(f64::from_le_bytes(self.take(8)?.try_into().unwrap())) }
    fn string_length(&mut self, length: u32) -> Result<String, String> { String::from_utf8(self.take(length as usize)?.to_vec()).map_err(|error| error.to_string()) }
    fn string(&mut self) -> Result<String, String> { let length = self.u32()?; if length == u32::MAX { return Err("required wire string is null".to_owned()); } self.string_length(length) }
    fn optional_string(&mut self) -> Result<Option<String>, String> { let length = self.u32()?; if length == u32::MAX { Ok(None) } else { self.string_length(length).map(Some) } }
    fn optional_f64(&mut self) -> Result<Option<f64>, String> { let value = self.f64()?; Ok((!value.is_nan()).then_some(value)) }
    fn count(&mut self) -> Result<usize, String> { let value = self.f64()?; if !value.is_finite() || value < 0.0 || value.fract() != 0.0 || value > usize::MAX as f64 { return Err("invalid simulation wire count".to_owned()); } Ok(value as usize) }
    fn optional_count(&mut self) -> Result<Option<usize>, String> { let value = self.f64()?; if value == -1.0 { return Ok(None); } if !value.is_finite() || value < 0.0 || value.fract() != 0.0 || value > usize::MAX as f64 { return Err("invalid optional simulation wire count".to_owned()); } Ok(Some(value as usize)) }

${readers}
}

pub(crate) fn decode_step_input(bytes: &[u8]) -> Result<WasmInput, String> {
    let mut reader = Reader { bytes, offset: 0 };
    if reader.u32()? != MAGIC { return Err("invalid simulation wire magic".to_owned()); }
    if reader.u32()? != VERSION { return Err("unsupported simulation wire version".to_owned()); }
    let input = reader.${snakeCase(wire.root)}()?;
    if reader.offset != bytes.len() { return Err("trailing simulation wire bytes".to_owned()); }
    Ok(input)
}
`;
}

function rustWireWrite(property, value) {
    const codec = wirePrimitive(property);
    if (codec === 'record') return `write_${snakeCase(referencedDefinition(property))}(writer, &${value})?;`;
    if (codec === 'recordArray') {
        const itemName = referencedDefinition(property);
        return `writer.u32(${value}.len() as u32); for item in &${value} { write_${snakeCase(itemName)}(writer, item)?; }`;
    }
    if (codec === 'eventArray') return `writer.u32(${value}.len() as u32); for item in &${value} { write_simulation_event(writer, item)?; }`;
    if (codec === 'boolArray') return `writer.u32(${value}.len() as u32); for item in &${value} { writer.u8(*item); }`;
    if (codec === 'stringArray') return `writer.u32(${value}.len() as u32); for item in &${value} { writer.string(item); }`;
    if (codec === 'count') return `writer.f64(${value} as f64);`;
    if (codec === 'optionalCount') return `writer.optional_count(${value});`;
    if (codec === 'optionalString') return `writer.optional_string(${value}.as_deref());`;
    if (codec === 'u8') return `writer.u8(${value});`;
    if (codec === 'string') return `writer.string(&${value});`;
    return `writer.${codec}(${value});`;
}

function rustEventWriteField(property, expression) {
    const codec = wirePrimitive(property);
    if (codec === 'record') return `write_${snakeCase(referencedDefinition(property))}(writer, ${expression})?;`;
    if (codec === 'count') return `writer.f64(*${expression} as f64);`;
    if (codec === 'string') return `writer.string(${expression});`;
    if (codec === 'u8') return `writer.u8(*${expression});`;
    if (codec === 'f64') return `writer.f64(*${expression});`;
    return `writer.${codec}(*${expression});`;
}

function generateRustEventEncoder(schema, wire) {
    const events = eventWireDefinition(schema, wire);
    const variants = schema.$defs.SimulationEvent.oneOf;
    const arms = events.map((event, index) => {
        const variant = variants[index];
        const fields = event.fields;
        const pattern = fields.length ? `{ ${fields.map(field => snakeCase(field)).join(', ')} }` : '';
        const lines = [`            writer.tag(${event.tag});`];
        for (const field of fields) {
            const property = variant.properties[field];
            const name = snakeCase(field);
            if (event.required.includes(field)) lines.push(`            ${rustEventWriteField(property, name)}`);
            else {
                lines.push(`            writer.u8(${name}.is_some());`, `            if let Some(value) = ${name}.as_ref() {`, `                ${rustEventWriteField(property, 'value')}`, '            }');
            }
        }
        return `        SimulationEvent::${pascalCase(event.type)} ${pattern} => {\n${lines.join('\n')}\n        }`;
    }).join(',\n');
    return `fn write_simulation_event(writer: &mut Writer, value: &SimulationEvent) -> Result<(), String> {\n    match value {\n${arms}\n    }\n    Ok(())\n}`;
}

function generateSimulationOutputWireRust(schema) {
    const wire = validateSimulationWireLayout(schema, 'output');
    const activeRecords = new Set();
    const pendingRecords = [wire.root];
    while (pendingRecords.length) {
        const name = pendingRecords.shift();
        if (activeRecords.has(name)) continue;
        activeRecords.add(name);
        const definition = schema.$defs[name];
        for (const property of Object.values(definition?.properties || {})) {
            const reference = referencedDefinition(property);
            if (reference && schema.$defs[reference]?.type === 'object') pendingRecords.push(reference);
        }
    }
    const records = Object.entries(wire.records).filter(([name]) => schema.$defs[name]?.type === 'object').map(([name, layout]) => {
        const definition = schema.$defs[name];
        const lines = layout.filter(entry => !Object.hasOwn(entry, 'excluded')).map(entry => rustWireWrite(definition.properties[entry.field], `value.${snakeCase(entry.field)}`));
        const allowDeadCode = activeRecords.has(name) ? '' : '#[allow(dead_code)]\n';
        return `${allowDeadCode}fn write_${snakeCase(name)}(writer: &mut Writer, value: &${definition['x-spaced-penguin-rust']?.name || name}) -> Result<(), String> {\n${lines.map(line => `    ${line}`).join('\n')}\n    Ok(())\n}`;
    }).join('\n\n');
    return `${banner('domain/simulation.schema.json x-spaced-penguin-wire output')}use crate::generated_game_objects::*;
use crate::generated_simulation_events::SimulationEvent;
use crate::generated_simulation_output::*;

const MAGIC: u32 = ${wire.magic};
const VERSION: u32 = ${wire.version};

struct Writer { bytes: Vec<u8> }
impl Writer {
    fn new() -> Self { Self { bytes: Vec::with_capacity(1024) } }
    fn u8(&mut self, value: bool) { self.bytes.push(value as u8); }
    fn tag(&mut self, value: u8) { self.bytes.push(value); }
    fn u32(&mut self, value: u32) { self.bytes.extend_from_slice(&value.to_le_bytes()); }
    fn f64(&mut self, value: f64) { self.bytes.extend_from_slice(&value.to_le_bytes()); }
    fn string(&mut self, value: &str) { self.u32(value.len() as u32); self.bytes.extend_from_slice(value.as_bytes()); }
    fn optional_string(&mut self, value: Option<&str>) { match value { Some(value) => self.string(value), None => self.u32(u32::MAX) } }
    #[allow(dead_code)]
    fn optional_count(&mut self, value: Option<usize>) { self.f64(value.map_or(-1.0, |value| value as f64)); }
}

${generateRustEventEncoder(schema, wire)}

${records}

pub(crate) fn encode_step_patch(value: &StepPatch) -> Result<Vec<u8>, String> {
    let mut writer = Writer::new();
    writer.u32(MAGIC);
    writer.u32(VERSION);
    write_step_patch(&mut writer, value)?;
    Ok(writer.bytes)
}
`;
}

async function main() {
    const [objects, simulation, level, versions] = await Promise.all([
        readJson('domain/gameObjects.schema.json'),
        readJson('domain/simulation.schema.json'),
        readJson('domain/level.schema.json'),
        readJson('domain/simulation-wire-versions.json').catch(() => null)
    ]);
    validateGameplaySimulationProjections(objects, simulation);
    validateSimulationWireLayout(simulation, 'input');
    validateSimulationWireLayout(simulation, 'output');
    const fingerprints = {
        input: computeSimulationWireFingerprint(simulation, 'input'),
        output: computeSimulationWireFingerprint(simulation, 'output')
    };
    if (versions) {
        const manifest = versions[simulation['x-spaced-penguin-wire'].name];
        if (!manifest || manifest.input?.[String(simulation['x-spaced-penguin-wire'].version)] !== fingerprints.input || manifest.output?.[String(simulation['x-spaced-penguin-wire'].output.version || simulation['x-spaced-penguin-wire'].version)] !== fingerprints.output) {
            throw new Error('simulation-wire-versions.json is stale; update the version/fingerprint declaration intentionally');
        }
    }
    const expandedLevel = expandLevelSchema(level, objects);
    const outputs = new Map([
        ['generated/js/gameObjectTypes.js', generateGameObjectJs(objects, level)],
        ['generated/js/simulationTypes.js', generateSimulationJs(simulation)],
        ['generated/js/simulationWire.js', generateSimulationWireJs(simulation)],
        ['generated/js/levelSchema.js', generateLevelJs(expandedLevel)],
        ['generated/rust/game_objects.rs', formatRust(generateRustModule(simulation, 'game_objects'))],
        ['generated/rust/simulation_state.rs', formatRust(generateRustModule(simulation, 'simulation_state'))],
        ['generated/rust/simulation_events.rs', formatRust(generateRustEvents(simulation))],
        ['generated/rust/simulation_output.rs', formatRust(generateRustModule(simulation, 'simulation_output'))],
        ['generated/rust/simulation_wire.rs', formatRust(generateSimulationWireRust(simulation))],
        ['generated/rust/simulation_output_wire.rs', formatRust(generateSimulationOutputWireRust(simulation))],
        ['generated/level.schema.json', stableJson(expandedLevel)]
    ]);
    const check = process.argv.includes('--check');
    const stale = [];
    for (const [path, content] of outputs) {
        const url = new URL(path, ROOT);
        if (check) {
            const current = await readFile(url, 'utf8').catch(() => null);
            if (current !== content) stale.push(path);
        } else {
            await writeFile(url, content);
        }
    }
    if (stale.length) {
        console.error(`Generated domain contracts are stale:\n${stale.map(path => `  ${path}`).join('\n')}`);
        process.exitCode = 1;
    } else {
        console.log(check ? 'Generated domain contracts are current.' : `Generated ${outputs.size} domain contract artifacts.`);
    }
}

const invokedDirectly = process.argv[1] && pathToFileURL(resolve(process.argv[1])).href === import.meta.url;
if (invokedDirectly) await main();
